#:schema node_modules/wrangler/config-schema.json
name = "codewizard-training"
workers_dev = true
upload_source_maps = true
compatibility_date = "2025-07-07"
compatibility_flags = [ "nodejs_compat", "nodejs_compat_populate_process_env" ]

route = { pattern = "codewizard.training", custom_domain = true, zone_id = "f5a6d096db660aa11d735007b54dd639" }

[[r2_buckets]]
binding = 'R2_Bucket'
bucket_name = 'codewizard-training'

[assets]
directory = "./dist"

[env.staging]
name = "codewizard-staging"
route = { pattern = "staging.codewizard.training", custom_domain = true, zone_id = "f5a6d096db660aa11d735007b54dd639" }

[[r2_buckets]]
binding = 'R2_Staging_Bucket'
bucket_name = 'codewizard-staging'
