services:
  cw-postgres:
    container_name: cw-postgres
    image: asjas/postgres-18.0-alpine3.22
    environment:
      - POSTGRES_USER=cw_user
      - POSTGRES_PASSWORD=cw_pass
      - POSTGRES_DB=cw_db
    volumes:
      - cw-postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    restart: always
  cw-dragonfly:
    container_name: cw-dragonfly
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.34.1
    volumes:
      - cw-dragonfly-data:/data
    ports:
      - "6379:6379"
    ulimits:
      memlock: -1
    restart: always

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    network_mode: host
    environment:
      - SERVICE_URL_GRAFANA_8888
      - GF_SERVER_ROOT_URL=${SERVICE_URL_GRAFANA}
      - GF_SERVER_DOMAIN=${SERVICE_URL_GRAFANA}
      - GF_SERVER_HTTP_PORT=8888
    volumes:
      - grafana-data:/var/lib/grafana
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://127.0.0.1:8888/api/health
      interval: 5s
      timeout: 20s
      retries: 10
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: host
    user: root
    volumes:
      - prometheus-data:/prometheus
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -qO-
        - http://localhost:9090
      interval: 5s
      timeout: 20s
      retries: 20
    depends_on:
      - node_exporter
    environment:
      - SERVICE_URL_DDGRAFANA_9090
      - PROMETHEUS_CONF_TRAEFIK_DOMAIN=${PROMETHEUS_CONF_TRAEFIK_DOMAIN}
      - PROMETHEUS_CONF_TRAEFIK_USER=${PROMETHEUS_CONF_TRAEFIK_USER}
      - PROMETHEUS_CONF_TRAEFIK_PASS=${PROMETHEUS_CONF_TRAEFIK_PASS}
      - PROMETHEUS_CONF_TRAEFIK_METRICS_PATH=${PROMETHEUS_CONF_TRAEFIK_METRICS_PATH:-/metrics}
      - PROMETHEUS_CONF_NAVIDROME_DOMAIN=${PROMETHEUS_CONF_NAVIDROME_DOMAIN}
      - PROMETHEUS_CONF_NAVIDROME_METRICS_PATH=${PROMETHEUS_CONF_NAVIDROME_METRICS_PATH}
    labels:
      - traefik.http.middlewares.authelia@file
    entrypoint:
      - /bin/sh
      - -c
      - |
        cat <<EOF > /prometheus/conf.yaml
        global:
          scrape_interval: 15s
        scrape_configs:
          - job_name: 'prometheus'
            scrape_interval: 5s
            static_configs:
              - targets: ['localhost:9090']
          - job_name: 'node_exporter'
            static_configs:
              - targets: ['node_exporter:9100']
          - job_name: 'traefik'
            metrics_path: ${PROMETHEUS_CONF_TRAEFIK_METRICS_PATH}
            basic_auth:
              username: '${PROMETHEUS_CONF_TRAEFIK_USER}'
              password: '${PROMETHEUS_CONF_TRAEFIK_PASS}'
            static_configs:
              - targets:
                  - ${PROMETHEUS_CONF_TRAEFIK_DOMAIN}
        EOF
        /bin/prometheus --config.file=/prometheus/conf.yaml

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    network_mode: host
    command:
      - --path.rootfs=/host
    pid: host
    volumes:
      - /:/host:ro,rslave

volumes:
  cw-postgres-data:
    external: false
  cw-dragonfly-data:
    external: false
  grafana-data:
    external: false
  prometheus-data:
    external: false
