services:
  cw-postgres:
    container_name: cw-postgres
    image: postgres:18.1-bookworm
    environment:
      - POSTGRES_USER=cw_user
      - POSTGRES_PASSWORD=cw_pass
      - POSTGRES_DB=cw_db
    volumes:
      - cw-postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    restart: always
  cw-dragonfly:
    container_name: cw-dragonfly
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.36.0
    volumes:
      - cw-dragonfly-data:/data
    environment:
      - DFLY_cache_mode=true
      - DFLY_snapshot_cron=0 */5 * * *
    ports:
      - "6379:6379"
    ulimits:
      memlock: -1
    restart: always

volumes:
  cw-postgres-data:
    external: false
  cw-dragonfly-data:
    external: false
