packages:
  - apps/**
  - marketing/**
  - packages/**

allowBuilds:
  argon2: true
  cypress: true
  esbuild: true
  libpq: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - argon2
  - cypress
  - esbuild
  - libpq
  - protobufjs
  - sharp
  - unrs-resolver
