packages:
  - apps/**
  - marketing/**
  - packages/**
  - tooling/**

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - argon2
  - cypress
  - esbuild
  - libpq
  - protobufjs
  - sharp
  - unrs-resolver
