# Listen
listen_addresses = '*'

# Memory Settings
shared_buffers = 16GB
work_mem = 16MB
maintenance_work_mem = 1GB
effective_cache_size = 36GB

# Connection Settings
max_connections = 150
superuser_reserved_connections = 3

# WAL Settings
wal_level = replica
wal_buffers = 16MB
checkpoint_timeout = 10min
checkpoint_completion_target = 0.9
min_wal_size = 80MB
max_wal_size = 6GB
wal_compression = on

# Parallelism
max_parallel_workers_per_gather = 8
max_parallel_workers = 16
parallel_leader_participation = on

# Autovacuum
autovacuum = on
autovacuum_vacuum_cost_limit = 4000
autovacuum_vacuum_scale_factor = 0.1

# Planner
random_page_cost = 1.0
effective_io_concurrency = 1000

# Logging
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_rotation_age = '1d'
log_min_duration_statement = 1000
log_connections = 'on'
log_disconnections = 'on'
log_lock_waits = 'on'
logging_collector = on
log_min_messages = 'warning'
log_statement = 'ddl'
log_destination = 'stderr'
log_parameter_max_length = 0
log_parameter_max_length_on_error = 0

# Query performance tracking
shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.track = all
