pid /run/nginx/nginx.pid;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    # Compression
    gzip on;
    gzip_types text/css application/javascript text/plain application/json image/svg+xml;

    # Rate limiting
    limit_req_zone $binary_remote_addr zone=dynamic:10m rate=1000r/m;
    limit_req zone=dynamic burst=1000 nodelay;

    # Logging
    access_log /dev/stdout;
    error_log  /dev/stderr warn;
    log_format json '{"time": "$time_iso8601", "remote_addr": "$remote_addr", "request": "$request", "status": $status, "body_bytes_sent": $body_bytes_sent, "http_referer": "$http_referer", "http_user_agent": "$http_user_agent"}';

    # File cache
    open_file_cache max=1000 inactive=20s;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors on;

    client_max_body_size 2m;

    server_tokens off;

    server {
        listen 80;
        root /srv/app;

        # Global headers
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' https://static.cloudflareinsights.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self';";
        add_header Permissions-Policy interest-cohort=();
        add_header Strict-Transport-Security max-age=31556952;
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options DENY;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Cross-Origin-Embedder-Policy "require-corp" always;
        add_header Cross-Origin-Opener-Policy "same-origin" always;
        add_header Cross-Origin-Resource-Policy "same-origin" always;

        # Location for /sw.js
        location = /sw.js {
            try_files /sw.js =404;
            add_header Cache-Control "public, no-cache, max-age=0";
            add_header Content-Type application/javascript;
        }

        # Location for immutable assets
        location ~* \.(js)$ {
            add_header Cache-Control "public, immutable, max-age=31536000";
            add_header Content-Type application/javascript;
        }

        location ~* \.(css)$ {
            add_header Cache-Control "public, immutable, max-age=31536000";
            add_header Content-Type text/css;
        }

        # Location for other static assets
        location ~* \.(txt|xml|json|svg|png|jpg|jpeg|gif|webp|ico|webmanifest|woff2|woff|ttf|eot|otf)$ {
            add_header Cache-Control "public, max-age=3600";

            types {
              text/plain                  txt;
              application/xml             xml;
              image/jpeg                  jpg jpeg;
              application/json            json;
              image/svg+xml               svg;
              image/png                   png;
              image/gif                   gif;
              image/webp                  webp;
              image/x-icon                ico;
              application/manifest+json   webmanifest;
              font/woff2                  woff2;
              font/woff                   woff;
              font/ttf                    ttf;
              font/otf                    otf;
            }
        }

        # Default location
        location / {
            try_files $uri $uri/ /index.html;
            add_header Cache-Control "public, max-age=300, must-revalidate";
        }

        # Health check
        location = /health {
            return 200 '{"status": "ok"}';
            add_header Content-Type application/json;
        }

        # Method not allowed
        if ($request_method !~ ^(GET|HEAD|POST)$ ) {
          return 405;
        }

        sendfile        on;
        tcp_nopush      on;
        tcp_nodelay     on;
        keepalive_timeout  65;
    }
}
