DROP INDEX "my_schema"."account_account_id_idx";--> statement-breakpoint
DROP INDEX "my_schema"."account_provider_id_idx";--> statement-breakpoint
DROP INDEX "my_schema"."account_access_token_idx";--> statement-breakpoint
DROP INDEX "my_schema"."account_refresh_token_idx";--> statement-breakpoint
DROP INDEX "my_schema"."account_id_token_idx";--> statement-breakpoint
DROP INDEX "my_schema"."account_user_id_idx";--> statement-breakpoint
DROP INDEX "my_schema"."account_refresh_token_expires_at_idx";--> statement-breakpoint
DROP INDEX "my_schema"."account_access_token_expires_at_idx";--> statement-breakpoint
DROP INDEX "my_schema"."account_provider_user_unique_idx";--> statement-breakpoint
DROP INDEX "my_schema"."invitation_email_idx";--> statement-breakpoint
DROP INDEX "my_schema"."invitation_status_idx";--> statement-breakpoint
DROP INDEX "my_schema"."invitation_organization_idx";--> statement-breakpoint
DROP INDEX "my_schema"."invitation_inviter_idx";--> statement-breakpoint
DROP INDEX "my_schema"."invitation_organization_email_unique_idx";--> statement-breakpoint
DROP INDEX "my_schema"."member_organization_idx";--> statement-breakpoint
DROP INDEX "my_schema"."member_user_idx";--> statement-breakpoint
DROP INDEX "my_schema"."member_role_idx";--> statement-breakpoint
DROP INDEX "my_schema"."member_organization_user_unique_idx";--> statement-breakpoint
DROP INDEX "my_schema"."organization_name_idx";--> statement-breakpoint
DROP INDEX "my_schema"."organization_slug_idx";--> statement-breakpoint
DROP INDEX "my_schema"."organization_created_at_idx";--> statement-breakpoint
DROP INDEX "my_schema"."organization_updated_at_idx";--> statement-breakpoint
DROP INDEX "my_schema"."session_user_idx";--> statement-breakpoint
DROP INDEX "my_schema"."session_ip_address_idx";--> statement-breakpoint
DROP INDEX "my_schema"."session_user_agent_idx";--> statement-breakpoint
DROP INDEX "my_schema"."session_expires_at_idx";--> statement-breakpoint
DROP INDEX "my_schema"."session_impersonated_by_idx";--> statement-breakpoint
DROP INDEX "my_schema"."user_name_idx";--> statement-breakpoint
DROP INDEX "my_schema"."user_username_idx";--> statement-breakpoint
DROP INDEX "my_schema"."user_role_idx";--> statement-breakpoint
DROP INDEX "my_schema"."user_banned_idx";--> statement-breakpoint
DROP INDEX "my_schema"."user_email_verified_idx";--> statement-breakpoint
DROP INDEX "my_schema"."user_created_at_idx";--> statement-breakpoint
DROP INDEX "my_schema"."user_updated_at_idx";--> statement-breakpoint
DROP INDEX "my_schema"."verification_identifier_idx";--> statement-breakpoint
DROP INDEX "my_schema"."verification_value_idx";--> statement-breakpoint
DROP INDEX "my_schema"."verification_expires_at_idx";