/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TermsRouteImport } from "./routes/terms"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as PrivacyRouteImport } from "./routes/privacy"
import { Route as DownloadsRouteImport } from "./routes/downloads"
import { Route as AdminRouteImport } from "./routes/admin"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as authRouteRouteImport } from "./routes/(auth)/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as BlogIndexRouteImport } from "./routes/blog/index"
import { Route as BlogSlugRouteImport } from "./routes/blog/$slug"
import { Route as AdminUsersRouteImport } from "./routes/admin.users"
import { Route as AuthDashboardRouteImport } from "./routes/_auth.dashboard"
import { Route as authSignupRouteImport } from "./routes/(auth)/signup"
import { Route as authSigninRouteImport } from "./routes/(auth)/signin"
import { Route as authResetPasswordRouteImport } from "./routes/(auth)/reset-password"
import { Route as EducationCoursesRouteRouteImport } from "./routes/education/courses/route"
import { Route as EducationCoursesIndexRouteImport } from "./routes/education/courses/index"
import { Route as EducationCoursesCourseRouteRouteImport } from "./routes/education/courses/$course/route"
import { Route as EducationCoursesCourseIndexRouteImport } from "./routes/education/courses/$course/index"

const TermsRoute = TermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: "/downloads",
  path: "/downloads",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: "/(auth)",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: "/blog/",
  path: "/blog/",
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: "/blog/$slug",
  path: "/blog/$slug",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AdminRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => authRouteRoute,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => authRouteRoute,
} as any)
const EducationCoursesRouteRoute = EducationCoursesRouteRouteImport.update({
  id: "/education/courses",
  path: "/education/courses",
  getParentRoute: () => rootRouteImport,
} as any)
const EducationCoursesIndexRoute = EducationCoursesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => EducationCoursesRouteRoute,
} as any)
const EducationCoursesCourseRouteRoute =
  EducationCoursesCourseRouteRouteImport.update({
    id: "/$course",
    path: "/$course",
    getParentRoute: () => EducationCoursesRouteRoute,
  } as any)
const EducationCoursesCourseIndexRoute =
  EducationCoursesCourseIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => EducationCoursesCourseRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof authRouteRouteWithChildren
  "/admin": typeof AdminRouteWithChildren
  "/downloads": typeof DownloadsRoute
  "/privacy": typeof PrivacyRoute
  "/settings": typeof SettingsRoute
  "/terms": typeof TermsRoute
  "/education/courses": typeof EducationCoursesRouteRouteWithChildren
  "/reset-password": typeof authResetPasswordRoute
  "/signin": typeof authSigninRoute
  "/signup": typeof authSignupRoute
  "/dashboard": typeof AuthDashboardRoute
  "/admin/users": typeof AdminUsersRoute
  "/blog/$slug": typeof BlogSlugRoute
  "/blog": typeof BlogIndexRoute
  "/education/courses/$course": typeof EducationCoursesCourseRouteRouteWithChildren
  "/education/courses/": typeof EducationCoursesIndexRoute
  "/education/courses/$course/": typeof EducationCoursesCourseIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof authRouteRouteWithChildren
  "/admin": typeof AdminRouteWithChildren
  "/downloads": typeof DownloadsRoute
  "/privacy": typeof PrivacyRoute
  "/settings": typeof SettingsRoute
  "/terms": typeof TermsRoute
  "/reset-password": typeof authResetPasswordRoute
  "/signin": typeof authSigninRoute
  "/signup": typeof authSignupRoute
  "/dashboard": typeof AuthDashboardRoute
  "/admin/users": typeof AdminUsersRoute
  "/blog/$slug": typeof BlogSlugRoute
  "/blog": typeof BlogIndexRoute
  "/education/courses": typeof EducationCoursesIndexRoute
  "/education/courses/$course": typeof EducationCoursesCourseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/(auth)": typeof authRouteRouteWithChildren
  "/_auth": typeof AuthRouteWithChildren
  "/admin": typeof AdminRouteWithChildren
  "/downloads": typeof DownloadsRoute
  "/privacy": typeof PrivacyRoute
  "/settings": typeof SettingsRoute
  "/terms": typeof TermsRoute
  "/education/courses": typeof EducationCoursesRouteRouteWithChildren
  "/(auth)/reset-password": typeof authResetPasswordRoute
  "/(auth)/signin": typeof authSigninRoute
  "/(auth)/signup": typeof authSignupRoute
  "/_auth/dashboard": typeof AuthDashboardRoute
  "/admin/users": typeof AdminUsersRoute
  "/blog/$slug": typeof BlogSlugRoute
  "/blog/": typeof BlogIndexRoute
  "/education/courses/$course": typeof EducationCoursesCourseRouteRouteWithChildren
  "/education/courses/": typeof EducationCoursesIndexRoute
  "/education/courses/$course/": typeof EducationCoursesCourseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/admin"
    | "/downloads"
    | "/privacy"
    | "/settings"
    | "/terms"
    | "/education/courses"
    | "/reset-password"
    | "/signin"
    | "/signup"
    | "/dashboard"
    | "/admin/users"
    | "/blog/$slug"
    | "/blog"
    | "/education/courses/$course"
    | "/education/courses/"
    | "/education/courses/$course/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/admin"
    | "/downloads"
    | "/privacy"
    | "/settings"
    | "/terms"
    | "/reset-password"
    | "/signin"
    | "/signup"
    | "/dashboard"
    | "/admin/users"
    | "/blog/$slug"
    | "/blog"
    | "/education/courses"
    | "/education/courses/$course"
  id:
    | "__root__"
    | "/"
    | "/(auth)"
    | "/_auth"
    | "/admin"
    | "/downloads"
    | "/privacy"
    | "/settings"
    | "/terms"
    | "/education/courses"
    | "/(auth)/reset-password"
    | "/(auth)/signin"
    | "/(auth)/signup"
    | "/_auth/dashboard"
    | "/admin/users"
    | "/blog/$slug"
    | "/blog/"
    | "/education/courses/$course"
    | "/education/courses/"
    | "/education/courses/$course/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DownloadsRoute: typeof DownloadsRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  EducationCoursesRouteRoute: typeof EducationCoursesRouteRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/terms": {
      id: "/terms"
      path: "/terms"
      fullPath: "/terms"
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/privacy": {
      id: "/privacy"
      path: "/privacy"
      fullPath: "/privacy"
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/downloads": {
      id: "/downloads"
      path: "/downloads"
      fullPath: "/downloads"
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin": {
      id: "/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(auth)": {
      id: "/(auth)"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/blog/": {
      id: "/blog/"
      path: "/blog"
      fullPath: "/blog"
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/blog/$slug": {
      id: "/blog/$slug"
      path: "/blog/$slug"
      fullPath: "/blog/$slug"
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/users": {
      id: "/admin/users"
      path: "/users"
      fullPath: "/admin/users"
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    "/_auth/dashboard": {
      id: "/_auth/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    "/(auth)/signup": {
      id: "/(auth)/signup"
      path: "/signup"
      fullPath: "/signup"
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    "/(auth)/signin": {
      id: "/(auth)/signin"
      path: "/signin"
      fullPath: "/signin"
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof authRouteRoute
    }
    "/(auth)/reset-password": {
      id: "/(auth)/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    "/education/courses": {
      id: "/education/courses"
      path: "/education/courses"
      fullPath: "/education/courses"
      preLoaderRoute: typeof EducationCoursesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/education/courses/": {
      id: "/education/courses/"
      path: "/"
      fullPath: "/education/courses/"
      preLoaderRoute: typeof EducationCoursesIndexRouteImport
      parentRoute: typeof EducationCoursesRouteRoute
    }
    "/education/courses/$course": {
      id: "/education/courses/$course"
      path: "/$course"
      fullPath: "/education/courses/$course"
      preLoaderRoute: typeof EducationCoursesCourseRouteRouteImport
      parentRoute: typeof EducationCoursesRouteRoute
    }
    "/education/courses/$course/": {
      id: "/education/courses/$course/"
      path: "/"
      fullPath: "/education/courses/$course/"
      preLoaderRoute: typeof EducationCoursesCourseIndexRouteImport
      parentRoute: typeof EducationCoursesCourseRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authResetPasswordRoute: authResetPasswordRoute,
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EducationCoursesCourseRouteRouteChildren {
  EducationCoursesCourseIndexRoute: typeof EducationCoursesCourseIndexRoute
}

const EducationCoursesCourseRouteRouteChildren: EducationCoursesCourseRouteRouteChildren =
  {
    EducationCoursesCourseIndexRoute: EducationCoursesCourseIndexRoute,
  }

const EducationCoursesCourseRouteRouteWithChildren =
  EducationCoursesCourseRouteRoute._addFileChildren(
    EducationCoursesCourseRouteRouteChildren,
  )

interface EducationCoursesRouteRouteChildren {
  EducationCoursesCourseRouteRoute: typeof EducationCoursesCourseRouteRouteWithChildren
  EducationCoursesIndexRoute: typeof EducationCoursesIndexRoute
}

const EducationCoursesRouteRouteChildren: EducationCoursesRouteRouteChildren = {
  EducationCoursesCourseRouteRoute:
    EducationCoursesCourseRouteRouteWithChildren,
  EducationCoursesIndexRoute: EducationCoursesIndexRoute,
}

const EducationCoursesRouteRouteWithChildren =
  EducationCoursesRouteRoute._addFileChildren(
    EducationCoursesRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DownloadsRoute: DownloadsRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  EducationCoursesRouteRoute: EducationCoursesRouteRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
