/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TermsRouteImport } from "./routes/terms"
import { Route as PrivacyRouteImport } from "./routes/privacy"
import { Route as DownloadsRouteImport } from "./routes/downloads"
import { Route as CookiesRouteImport } from "./routes/cookies"
import { Route as SupportRouteRouteImport } from "./routes/support/route"
import { Route as AuthenticatedRouteRouteImport } from "./routes/_authenticated/route"
import { Route as authRouteRouteImport } from "./routes/(auth)/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as SupportIndexRouteImport } from "./routes/support/index"
import { Route as BlogIndexRouteImport } from "./routes/blog/index"
import { Route as VerifyEmailTokenRouteImport } from "./routes/verify-email.$token"
import { Route as SupportCreateTicketRouteImport } from "./routes/support/create-ticket"
import { Route as BlogSlugRouteImport } from "./routes/blog/$slug"
import { Route as AuthenticatedPurchasesRouteImport } from "./routes/_authenticated/purchases"
import { Route as AuthenticatedProfileRouteImport } from "./routes/_authenticated/profile"
import { Route as AuthenticatedDashboardRouteImport } from "./routes/_authenticated/dashboard"
import { Route as AuthenticatedChatRouteImport } from "./routes/_authenticated/chat"
import { Route as AuthenticatedAccountRouteImport } from "./routes/_authenticated/account"
import { Route as authSignupRouteImport } from "./routes/(auth)/signup"
import { Route as authSigninRouteImport } from "./routes/(auth)/signin"
import { Route as authResetPasswordRouteImport } from "./routes/(auth)/reset-password"
import { Route as EducationCoursesRouteRouteImport } from "./routes/education/courses/route"
import { Route as AuthenticatedAdminRouteRouteImport } from "./routes/_authenticated/admin/route"
import { Route as SupportSupportTicketIndexRouteImport } from "./routes/support/$supportTicket/index"
import { Route as EducationCoursesIndexRouteImport } from "./routes/education/courses/index"
import { Route as AuthenticatedChatChannelIdRouteImport } from "./routes/_authenticated/chat.$channelId"
import { Route as AuthenticatedAdminUsersRouteImport } from "./routes/_authenticated/admin/users"
import { Route as AuthenticatedAdminPurchasesRouteImport } from "./routes/_authenticated/admin/purchases"
import { Route as AuthenticatedAdminCoursesRouteImport } from "./routes/_authenticated/admin/courses"
import { Route as SupportSupportTicketEditRouteRouteImport } from "./routes/support/$supportTicket/edit/route"
import { Route as EducationCoursesCourseRouteRouteImport } from "./routes/education/courses/$course/route"
import { Route as SupportSupportTicketEditIndexRouteImport } from "./routes/support/$supportTicket/edit/index"
import { Route as EducationCoursesCourseIndexRouteImport } from "./routes/education/courses/$course/index"
import { Route as AuthenticatedAdminCouponsIndexRouteImport } from "./routes/_authenticated/admin/coupons/index"
import { Route as AuthenticatedAdminCoursesInstructorNotesRouteImport } from "./routes/_authenticated/admin/courses.instructor-notes"
import { Route as AuthenticatedAdminCoursesFaqRouteImport } from "./routes/_authenticated/admin/courses.faq"
import { Route as AuthenticatedAdminCouponsCreateIndexRouteImport } from "./routes/_authenticated/admin/coupons/create/index"
import { Route as AuthenticatedAdminCouponsEditIndexCouponIdRouteImport } from "./routes/_authenticated/admin/coupons/edit/index.$couponId"

const TermsRoute = TermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: "/downloads",
  path: "/downloads",
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: "/cookies",
  path: "/cookies",
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRouteRoute = SupportRouteRouteImport.update({
  id: "/support",
  path: "/support",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: "/(auth)",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SupportRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: "/blog/",
  path: "/blog/",
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailTokenRoute = VerifyEmailTokenRouteImport.update({
  id: "/verify-email/$token",
  path: "/verify-email/$token",
  getParentRoute: () => rootRouteImport,
} as any)
const SupportCreateTicketRoute = SupportCreateTicketRouteImport.update({
  id: "/create-ticket",
  path: "/create-ticket",
  getParentRoute: () => SupportRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: "/blog/$slug",
  path: "/blog/$slug",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: "/purchases",
  path: "/purchases",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => authRouteRoute,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => authRouteRoute,
} as any)
const EducationCoursesRouteRoute = EducationCoursesRouteRouteImport.update({
  id: "/education/courses",
  path: "/education/courses",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SupportSupportTicketIndexRoute =
  SupportSupportTicketIndexRouteImport.update({
    id: "/$supportTicket/",
    path: "/$supportTicket/",
    getParentRoute: () => SupportRouteRoute,
  } as any)
const EducationCoursesIndexRoute = EducationCoursesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => EducationCoursesRouteRoute,
} as any)
const AuthenticatedChatChannelIdRoute =
  AuthenticatedChatChannelIdRouteImport.update({
    id: "/$channelId",
    path: "/$channelId",
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: "/users",
  path: "/users",
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPurchasesRoute =
  AuthenticatedAdminPurchasesRouteImport.update({
    id: "/purchases",
    path: "/purchases",
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: "/courses",
    path: "/courses",
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const SupportSupportTicketEditRouteRoute =
  SupportSupportTicketEditRouteRouteImport.update({
    id: "/$supportTicket/edit",
    path: "/$supportTicket/edit",
    getParentRoute: () => SupportRouteRoute,
  } as any)
const EducationCoursesCourseRouteRoute =
  EducationCoursesCourseRouteRouteImport.update({
    id: "/$course",
    path: "/$course",
    getParentRoute: () => EducationCoursesRouteRoute,
  } as any)
const SupportSupportTicketEditIndexRoute =
  SupportSupportTicketEditIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => SupportSupportTicketEditRouteRoute,
  } as any)
const EducationCoursesCourseIndexRoute =
  EducationCoursesCourseIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => EducationCoursesCourseRouteRoute,
  } as any)
const AuthenticatedAdminCouponsIndexRoute =
  AuthenticatedAdminCouponsIndexRouteImport.update({
    id: "/coupons/",
    path: "/coupons/",
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCoursesInstructorNotesRoute =
  AuthenticatedAdminCoursesInstructorNotesRouteImport.update({
    id: "/instructor-notes",
    path: "/instructor-notes",
    getParentRoute: () => AuthenticatedAdminCoursesRoute,
  } as any)
const AuthenticatedAdminCoursesFaqRoute =
  AuthenticatedAdminCoursesFaqRouteImport.update({
    id: "/faq",
    path: "/faq",
    getParentRoute: () => AuthenticatedAdminCoursesRoute,
  } as any)
const AuthenticatedAdminCouponsCreateIndexRoute =
  AuthenticatedAdminCouponsCreateIndexRouteImport.update({
    id: "/coupons/create/",
    path: "/coupons/create/",
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCouponsEditIndexCouponIdRoute =
  AuthenticatedAdminCouponsEditIndexCouponIdRouteImport.update({
    id: "/coupons/edit/index/$couponId",
    path: "/coupons/edit/index/$couponId",
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/support": typeof SupportRouteRouteWithChildren
  "/cookies": typeof CookiesRoute
  "/downloads": typeof DownloadsRoute
  "/privacy": typeof PrivacyRoute
  "/terms": typeof TermsRoute
  "/admin": typeof AuthenticatedAdminRouteRouteWithChildren
  "/education/courses": typeof EducationCoursesRouteRouteWithChildren
  "/reset-password": typeof authResetPasswordRoute
  "/signin": typeof authSigninRoute
  "/signup": typeof authSignupRoute
  "/account": typeof AuthenticatedAccountRoute
  "/chat": typeof AuthenticatedChatRouteWithChildren
  "/dashboard": typeof AuthenticatedDashboardRoute
  "/profile": typeof AuthenticatedProfileRoute
  "/purchases": typeof AuthenticatedPurchasesRoute
  "/blog/$slug": typeof BlogSlugRoute
  "/support/create-ticket": typeof SupportCreateTicketRoute
  "/verify-email/$token": typeof VerifyEmailTokenRoute
  "/blog": typeof BlogIndexRoute
  "/support/": typeof SupportIndexRoute
  "/education/courses/$course": typeof EducationCoursesCourseRouteRouteWithChildren
  "/support/$supportTicket/edit": typeof SupportSupportTicketEditRouteRouteWithChildren
  "/admin/courses": typeof AuthenticatedAdminCoursesRouteWithChildren
  "/admin/purchases": typeof AuthenticatedAdminPurchasesRoute
  "/admin/users": typeof AuthenticatedAdminUsersRoute
  "/chat/$channelId": typeof AuthenticatedChatChannelIdRoute
  "/education/courses/": typeof EducationCoursesIndexRoute
  "/support/$supportTicket": typeof SupportSupportTicketIndexRoute
  "/admin/courses/faq": typeof AuthenticatedAdminCoursesFaqRoute
  "/admin/courses/instructor-notes": typeof AuthenticatedAdminCoursesInstructorNotesRoute
  "/admin/coupons": typeof AuthenticatedAdminCouponsIndexRoute
  "/education/courses/$course/": typeof EducationCoursesCourseIndexRoute
  "/support/$supportTicket/edit/": typeof SupportSupportTicketEditIndexRoute
  "/admin/coupons/create": typeof AuthenticatedAdminCouponsCreateIndexRoute
  "/admin/coupons/edit/index/$couponId": typeof AuthenticatedAdminCouponsEditIndexCouponIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/cookies": typeof CookiesRoute
  "/downloads": typeof DownloadsRoute
  "/privacy": typeof PrivacyRoute
  "/terms": typeof TermsRoute
  "/admin": typeof AuthenticatedAdminRouteRouteWithChildren
  "/reset-password": typeof authResetPasswordRoute
  "/signin": typeof authSigninRoute
  "/signup": typeof authSignupRoute
  "/account": typeof AuthenticatedAccountRoute
  "/chat": typeof AuthenticatedChatRouteWithChildren
  "/dashboard": typeof AuthenticatedDashboardRoute
  "/profile": typeof AuthenticatedProfileRoute
  "/purchases": typeof AuthenticatedPurchasesRoute
  "/blog/$slug": typeof BlogSlugRoute
  "/support/create-ticket": typeof SupportCreateTicketRoute
  "/verify-email/$token": typeof VerifyEmailTokenRoute
  "/blog": typeof BlogIndexRoute
  "/support": typeof SupportIndexRoute
  "/admin/courses": typeof AuthenticatedAdminCoursesRouteWithChildren
  "/admin/purchases": typeof AuthenticatedAdminPurchasesRoute
  "/admin/users": typeof AuthenticatedAdminUsersRoute
  "/chat/$channelId": typeof AuthenticatedChatChannelIdRoute
  "/education/courses": typeof EducationCoursesIndexRoute
  "/support/$supportTicket": typeof SupportSupportTicketIndexRoute
  "/admin/courses/faq": typeof AuthenticatedAdminCoursesFaqRoute
  "/admin/courses/instructor-notes": typeof AuthenticatedAdminCoursesInstructorNotesRoute
  "/admin/coupons": typeof AuthenticatedAdminCouponsIndexRoute
  "/education/courses/$course": typeof EducationCoursesCourseIndexRoute
  "/support/$supportTicket/edit": typeof SupportSupportTicketEditIndexRoute
  "/admin/coupons/create": typeof AuthenticatedAdminCouponsCreateIndexRoute
  "/admin/coupons/edit/index/$couponId": typeof AuthenticatedAdminCouponsEditIndexCouponIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/(auth)": typeof authRouteRouteWithChildren
  "/_authenticated": typeof AuthenticatedRouteRouteWithChildren
  "/support": typeof SupportRouteRouteWithChildren
  "/cookies": typeof CookiesRoute
  "/downloads": typeof DownloadsRoute
  "/privacy": typeof PrivacyRoute
  "/terms": typeof TermsRoute
  "/_authenticated/admin": typeof AuthenticatedAdminRouteRouteWithChildren
  "/education/courses": typeof EducationCoursesRouteRouteWithChildren
  "/(auth)/reset-password": typeof authResetPasswordRoute
  "/(auth)/signin": typeof authSigninRoute
  "/(auth)/signup": typeof authSignupRoute
  "/_authenticated/account": typeof AuthenticatedAccountRoute
  "/_authenticated/chat": typeof AuthenticatedChatRouteWithChildren
  "/_authenticated/dashboard": typeof AuthenticatedDashboardRoute
  "/_authenticated/profile": typeof AuthenticatedProfileRoute
  "/_authenticated/purchases": typeof AuthenticatedPurchasesRoute
  "/blog/$slug": typeof BlogSlugRoute
  "/support/create-ticket": typeof SupportCreateTicketRoute
  "/verify-email/$token": typeof VerifyEmailTokenRoute
  "/blog/": typeof BlogIndexRoute
  "/support/": typeof SupportIndexRoute
  "/education/courses/$course": typeof EducationCoursesCourseRouteRouteWithChildren
  "/support/$supportTicket/edit": typeof SupportSupportTicketEditRouteRouteWithChildren
  "/_authenticated/admin/courses": typeof AuthenticatedAdminCoursesRouteWithChildren
  "/_authenticated/admin/purchases": typeof AuthenticatedAdminPurchasesRoute
  "/_authenticated/admin/users": typeof AuthenticatedAdminUsersRoute
  "/_authenticated/chat/$channelId": typeof AuthenticatedChatChannelIdRoute
  "/education/courses/": typeof EducationCoursesIndexRoute
  "/support/$supportTicket/": typeof SupportSupportTicketIndexRoute
  "/_authenticated/admin/courses/faq": typeof AuthenticatedAdminCoursesFaqRoute
  "/_authenticated/admin/courses/instructor-notes": typeof AuthenticatedAdminCoursesInstructorNotesRoute
  "/_authenticated/admin/coupons/": typeof AuthenticatedAdminCouponsIndexRoute
  "/education/courses/$course/": typeof EducationCoursesCourseIndexRoute
  "/support/$supportTicket/edit/": typeof SupportSupportTicketEditIndexRoute
  "/_authenticated/admin/coupons/create/": typeof AuthenticatedAdminCouponsCreateIndexRoute
  "/_authenticated/admin/coupons/edit/index/$couponId": typeof AuthenticatedAdminCouponsEditIndexCouponIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/support"
    | "/cookies"
    | "/downloads"
    | "/privacy"
    | "/terms"
    | "/admin"
    | "/education/courses"
    | "/reset-password"
    | "/signin"
    | "/signup"
    | "/account"
    | "/chat"
    | "/dashboard"
    | "/profile"
    | "/purchases"
    | "/blog/$slug"
    | "/support/create-ticket"
    | "/verify-email/$token"
    | "/blog"
    | "/support/"
    | "/education/courses/$course"
    | "/support/$supportTicket/edit"
    | "/admin/courses"
    | "/admin/purchases"
    | "/admin/users"
    | "/chat/$channelId"
    | "/education/courses/"
    | "/support/$supportTicket"
    | "/admin/courses/faq"
    | "/admin/courses/instructor-notes"
    | "/admin/coupons"
    | "/education/courses/$course/"
    | "/support/$supportTicket/edit/"
    | "/admin/coupons/create"
    | "/admin/coupons/edit/index/$couponId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/cookies"
    | "/downloads"
    | "/privacy"
    | "/terms"
    | "/admin"
    | "/reset-password"
    | "/signin"
    | "/signup"
    | "/account"
    | "/chat"
    | "/dashboard"
    | "/profile"
    | "/purchases"
    | "/blog/$slug"
    | "/support/create-ticket"
    | "/verify-email/$token"
    | "/blog"
    | "/support"
    | "/admin/courses"
    | "/admin/purchases"
    | "/admin/users"
    | "/chat/$channelId"
    | "/education/courses"
    | "/support/$supportTicket"
    | "/admin/courses/faq"
    | "/admin/courses/instructor-notes"
    | "/admin/coupons"
    | "/education/courses/$course"
    | "/support/$supportTicket/edit"
    | "/admin/coupons/create"
    | "/admin/coupons/edit/index/$couponId"
  id:
    | "__root__"
    | "/"
    | "/(auth)"
    | "/_authenticated"
    | "/support"
    | "/cookies"
    | "/downloads"
    | "/privacy"
    | "/terms"
    | "/_authenticated/admin"
    | "/education/courses"
    | "/(auth)/reset-password"
    | "/(auth)/signin"
    | "/(auth)/signup"
    | "/_authenticated/account"
    | "/_authenticated/chat"
    | "/_authenticated/dashboard"
    | "/_authenticated/profile"
    | "/_authenticated/purchases"
    | "/blog/$slug"
    | "/support/create-ticket"
    | "/verify-email/$token"
    | "/blog/"
    | "/support/"
    | "/education/courses/$course"
    | "/support/$supportTicket/edit"
    | "/_authenticated/admin/courses"
    | "/_authenticated/admin/purchases"
    | "/_authenticated/admin/users"
    | "/_authenticated/chat/$channelId"
    | "/education/courses/"
    | "/support/$supportTicket/"
    | "/_authenticated/admin/courses/faq"
    | "/_authenticated/admin/courses/instructor-notes"
    | "/_authenticated/admin/coupons/"
    | "/education/courses/$course/"
    | "/support/$supportTicket/edit/"
    | "/_authenticated/admin/coupons/create/"
    | "/_authenticated/admin/coupons/edit/index/$couponId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SupportRouteRoute: typeof SupportRouteRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  DownloadsRoute: typeof DownloadsRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  EducationCoursesRouteRoute: typeof EducationCoursesRouteRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  VerifyEmailTokenRoute: typeof VerifyEmailTokenRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/terms": {
      id: "/terms"
      path: "/terms"
      fullPath: "/terms"
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/privacy": {
      id: "/privacy"
      path: "/privacy"
      fullPath: "/privacy"
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/downloads": {
      id: "/downloads"
      path: "/downloads"
      fullPath: "/downloads"
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/cookies": {
      id: "/cookies"
      path: "/cookies"
      fullPath: "/cookies"
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/support": {
      id: "/support"
      path: "/support"
      fullPath: "/support"
      preLoaderRoute: typeof SupportRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/(auth)": {
      id: "/(auth)"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/support/": {
      id: "/support/"
      path: "/"
      fullPath: "/support/"
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof SupportRouteRoute
    }
    "/blog/": {
      id: "/blog/"
      path: "/blog"
      fullPath: "/blog"
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/verify-email/$token": {
      id: "/verify-email/$token"
      path: "/verify-email/$token"
      fullPath: "/verify-email/$token"
      preLoaderRoute: typeof VerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/support/create-ticket": {
      id: "/support/create-ticket"
      path: "/create-ticket"
      fullPath: "/support/create-ticket"
      preLoaderRoute: typeof SupportCreateTicketRouteImport
      parentRoute: typeof SupportRouteRoute
    }
    "/blog/$slug": {
      id: "/blog/$slug"
      path: "/blog/$slug"
      fullPath: "/blog/$slug"
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated/purchases": {
      id: "/_authenticated/purchases"
      path: "/purchases"
      fullPath: "/purchases"
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/profile": {
      id: "/_authenticated/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/dashboard": {
      id: "/_authenticated/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/chat": {
      id: "/_authenticated/chat"
      path: "/chat"
      fullPath: "/chat"
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/account": {
      id: "/_authenticated/account"
      path: "/account"
      fullPath: "/account"
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/(auth)/signup": {
      id: "/(auth)/signup"
      path: "/signup"
      fullPath: "/signup"
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    "/(auth)/signin": {
      id: "/(auth)/signin"
      path: "/signin"
      fullPath: "/signin"
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof authRouteRoute
    }
    "/(auth)/reset-password": {
      id: "/(auth)/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    "/education/courses": {
      id: "/education/courses"
      path: "/education/courses"
      fullPath: "/education/courses"
      preLoaderRoute: typeof EducationCoursesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated/admin": {
      id: "/_authenticated/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/support/$supportTicket/": {
      id: "/support/$supportTicket/"
      path: "/$supportTicket"
      fullPath: "/support/$supportTicket"
      preLoaderRoute: typeof SupportSupportTicketIndexRouteImport
      parentRoute: typeof SupportRouteRoute
    }
    "/education/courses/": {
      id: "/education/courses/"
      path: "/"
      fullPath: "/education/courses/"
      preLoaderRoute: typeof EducationCoursesIndexRouteImport
      parentRoute: typeof EducationCoursesRouteRoute
    }
    "/_authenticated/chat/$channelId": {
      id: "/_authenticated/chat/$channelId"
      path: "/$channelId"
      fullPath: "/chat/$channelId"
      preLoaderRoute: typeof AuthenticatedChatChannelIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    "/_authenticated/admin/users": {
      id: "/_authenticated/admin/users"
      path: "/users"
      fullPath: "/admin/users"
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    "/_authenticated/admin/purchases": {
      id: "/_authenticated/admin/purchases"
      path: "/purchases"
      fullPath: "/admin/purchases"
      preLoaderRoute: typeof AuthenticatedAdminPurchasesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    "/_authenticated/admin/courses": {
      id: "/_authenticated/admin/courses"
      path: "/courses"
      fullPath: "/admin/courses"
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    "/support/$supportTicket/edit": {
      id: "/support/$supportTicket/edit"
      path: "/$supportTicket/edit"
      fullPath: "/support/$supportTicket/edit"
      preLoaderRoute: typeof SupportSupportTicketEditRouteRouteImport
      parentRoute: typeof SupportRouteRoute
    }
    "/education/courses/$course": {
      id: "/education/courses/$course"
      path: "/$course"
      fullPath: "/education/courses/$course"
      preLoaderRoute: typeof EducationCoursesCourseRouteRouteImport
      parentRoute: typeof EducationCoursesRouteRoute
    }
    "/support/$supportTicket/edit/": {
      id: "/support/$supportTicket/edit/"
      path: "/"
      fullPath: "/support/$supportTicket/edit/"
      preLoaderRoute: typeof SupportSupportTicketEditIndexRouteImport
      parentRoute: typeof SupportSupportTicketEditRouteRoute
    }
    "/education/courses/$course/": {
      id: "/education/courses/$course/"
      path: "/"
      fullPath: "/education/courses/$course/"
      preLoaderRoute: typeof EducationCoursesCourseIndexRouteImport
      parentRoute: typeof EducationCoursesCourseRouteRoute
    }
    "/_authenticated/admin/coupons/": {
      id: "/_authenticated/admin/coupons/"
      path: "/coupons"
      fullPath: "/admin/coupons"
      preLoaderRoute: typeof AuthenticatedAdminCouponsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    "/_authenticated/admin/courses/instructor-notes": {
      id: "/_authenticated/admin/courses/instructor-notes"
      path: "/instructor-notes"
      fullPath: "/admin/courses/instructor-notes"
      preLoaderRoute: typeof AuthenticatedAdminCoursesInstructorNotesRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesRoute
    }
    "/_authenticated/admin/courses/faq": {
      id: "/_authenticated/admin/courses/faq"
      path: "/faq"
      fullPath: "/admin/courses/faq"
      preLoaderRoute: typeof AuthenticatedAdminCoursesFaqRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesRoute
    }
    "/_authenticated/admin/coupons/create/": {
      id: "/_authenticated/admin/coupons/create/"
      path: "/coupons/create"
      fullPath: "/admin/coupons/create"
      preLoaderRoute: typeof AuthenticatedAdminCouponsCreateIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    "/_authenticated/admin/coupons/edit/index/$couponId": {
      id: "/_authenticated/admin/coupons/edit/index/$couponId"
      path: "/coupons/edit/index/$couponId"
      fullPath: "/admin/coupons/edit/index/$couponId"
      preLoaderRoute: typeof AuthenticatedAdminCouponsEditIndexCouponIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authResetPasswordRoute: authResetPasswordRoute,
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedAdminCoursesRouteChildren {
  AuthenticatedAdminCoursesFaqRoute: typeof AuthenticatedAdminCoursesFaqRoute
  AuthenticatedAdminCoursesInstructorNotesRoute: typeof AuthenticatedAdminCoursesInstructorNotesRoute
}

const AuthenticatedAdminCoursesRouteChildren: AuthenticatedAdminCoursesRouteChildren =
  {
    AuthenticatedAdminCoursesFaqRoute: AuthenticatedAdminCoursesFaqRoute,
    AuthenticatedAdminCoursesInstructorNotesRoute:
      AuthenticatedAdminCoursesInstructorNotesRoute,
  }

const AuthenticatedAdminCoursesRouteWithChildren =
  AuthenticatedAdminCoursesRoute._addFileChildren(
    AuthenticatedAdminCoursesRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRouteWithChildren
  AuthenticatedAdminPurchasesRoute: typeof AuthenticatedAdminPurchasesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminCouponsIndexRoute: typeof AuthenticatedAdminCouponsIndexRoute
  AuthenticatedAdminCouponsCreateIndexRoute: typeof AuthenticatedAdminCouponsCreateIndexRoute
  AuthenticatedAdminCouponsEditIndexCouponIdRoute: typeof AuthenticatedAdminCouponsEditIndexCouponIdRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRouteWithChildren,
    AuthenticatedAdminPurchasesRoute: AuthenticatedAdminPurchasesRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminCouponsIndexRoute: AuthenticatedAdminCouponsIndexRoute,
    AuthenticatedAdminCouponsCreateIndexRoute:
      AuthenticatedAdminCouponsCreateIndexRoute,
    AuthenticatedAdminCouponsEditIndexCouponIdRoute:
      AuthenticatedAdminCouponsEditIndexCouponIdRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatChannelIdRoute: typeof AuthenticatedChatChannelIdRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatChannelIdRoute: AuthenticatedChatChannelIdRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SupportSupportTicketEditRouteRouteChildren {
  SupportSupportTicketEditIndexRoute: typeof SupportSupportTicketEditIndexRoute
}

const SupportSupportTicketEditRouteRouteChildren: SupportSupportTicketEditRouteRouteChildren =
  {
    SupportSupportTicketEditIndexRoute: SupportSupportTicketEditIndexRoute,
  }

const SupportSupportTicketEditRouteRouteWithChildren =
  SupportSupportTicketEditRouteRoute._addFileChildren(
    SupportSupportTicketEditRouteRouteChildren,
  )

interface SupportRouteRouteChildren {
  SupportCreateTicketRoute: typeof SupportCreateTicketRoute
  SupportIndexRoute: typeof SupportIndexRoute
  SupportSupportTicketEditRouteRoute: typeof SupportSupportTicketEditRouteRouteWithChildren
  SupportSupportTicketIndexRoute: typeof SupportSupportTicketIndexRoute
}

const SupportRouteRouteChildren: SupportRouteRouteChildren = {
  SupportCreateTicketRoute: SupportCreateTicketRoute,
  SupportIndexRoute: SupportIndexRoute,
  SupportSupportTicketEditRouteRoute:
    SupportSupportTicketEditRouteRouteWithChildren,
  SupportSupportTicketIndexRoute: SupportSupportTicketIndexRoute,
}

const SupportRouteRouteWithChildren = SupportRouteRoute._addFileChildren(
  SupportRouteRouteChildren,
)

interface EducationCoursesCourseRouteRouteChildren {
  EducationCoursesCourseIndexRoute: typeof EducationCoursesCourseIndexRoute
}

const EducationCoursesCourseRouteRouteChildren: EducationCoursesCourseRouteRouteChildren =
  {
    EducationCoursesCourseIndexRoute: EducationCoursesCourseIndexRoute,
  }

const EducationCoursesCourseRouteRouteWithChildren =
  EducationCoursesCourseRouteRoute._addFileChildren(
    EducationCoursesCourseRouteRouteChildren,
  )

interface EducationCoursesRouteRouteChildren {
  EducationCoursesCourseRouteRoute: typeof EducationCoursesCourseRouteRouteWithChildren
  EducationCoursesIndexRoute: typeof EducationCoursesIndexRoute
}

const EducationCoursesRouteRouteChildren: EducationCoursesRouteRouteChildren = {
  EducationCoursesCourseRouteRoute:
    EducationCoursesCourseRouteRouteWithChildren,
  EducationCoursesIndexRoute: EducationCoursesIndexRoute,
}

const EducationCoursesRouteRouteWithChildren =
  EducationCoursesRouteRoute._addFileChildren(
    EducationCoursesRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SupportRouteRoute: SupportRouteRouteWithChildren,
  CookiesRoute: CookiesRoute,
  DownloadsRoute: DownloadsRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  EducationCoursesRouteRoute: EducationCoursesRouteRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  VerifyEmailTokenRoute: VerifyEmailTokenRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
