/**
 * TranscriptEditorSection — admin panel for uploading and managing a lesson
 * transcript.
 *
 * Phase 2 capabilities:
 *   - Displays the current transcript status (cue count, duration, source).
 *   - VTT file upload: reads the file, parses it, shows a preview.
 *   - Parse errors / warnings shown inline with line numbers.
 *   - Calls `onTranscriptChange` with the new `TranscriptData` payload.
 *   - Clear button to remove an uploaded transcript.
 */
import { useRef, useState } from "react";
import type {
  TranscriptData,
  VttParseResult,
  VttParseWarning,
} from "~/lib/transcript";
import { buildTranscriptData, formatCueTime, parseVtt } from "~/lib/transcript";
import { cn } from "~/lib/utils";

// ---------------------------------------------------------------------------
// Props
// ---------------------------------------------------------------------------

interface TranscriptEditorSectionProps {
  /**
   * Current raw transcription value from the lesson (may be any DB shape).
   * Pass the existing lesson transcription so the section can show its status.
   */
  currentTranscription: unknown;
  /**
   * Called when the admin has parsed a valid VTT file and wants to apply it.
   * Pass `null` to clear the transcript.
   */
  onTranscriptChange: (data: TranscriptData | null) => void;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function formatMs(ms: number): string {
  const totalSeconds = Math.floor(ms / 1000);
  const m = Math.floor(totalSeconds / 60);
  const s = totalSeconds % 60;
  return `${m}:${s.toString().padStart(2, "0")}`;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

/**
 * Admin sub-panel for lesson transcript management.
 *
 * Built with accessibility in mind, but manual review is still recommended.
 */
export function TranscriptEditorSection({
  currentTranscription,
  onTranscriptChange,
}: TranscriptEditorSectionProps) {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [parseResult, setParseResult] = useState<VttParseResult | null>(null);
  const [pendingData, setPendingData] = useState<TranscriptData | null>(null);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [fileName, setFileName] = useState<string | null>(null);

  // Detect whether there is already a saved transcript
  const hasExistingTranscript =
    currentTranscription != null &&
    typeof currentTranscription === "object" &&
    "version" in (currentTranscription as object) &&
    (currentTranscription as { version: unknown }).version === 1;

  const existingData = hasExistingTranscript
    ? (currentTranscription as TranscriptData)
    : null;

  // ---------------------------------------------------------------------------
  // File handling
  // ---------------------------------------------------------------------------

  function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!file.name.toLowerCase().endsWith(".vtt")) {
      setUploadError("Only .vtt files are supported.");
      setParseResult(null);
      setPendingData(null);
      setFileName(null);
      return;
    }

    setUploadError(null);
    setFileName(file.name);

    const reader = new FileReader();
    reader.onload = (event) => {
      const text = event.target?.result;
      if (typeof text !== "string") {
        setUploadError("Failed to read file.");
        return;
      }

      const result = parseVtt(text);
      setParseResult(result);

      if (result.cues.length === 0) {
        setUploadError("No valid cues were found in this VTT file.");
        setPendingData(null);
        return;
      }

      const data = buildTranscriptData(result, {
        language: "en",
        source: "manual",
        isAutoGenerated: false,
      });
      setPendingData(data);
    };
    reader.readAsText(file);
  }

  function handleApply() {
    if (!pendingData) return;
    onTranscriptChange(pendingData);
    // Reset local state after applying
    setParseResult(null);
    setPendingData(null);
    setFileName(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  }

  function handleClear() {
    onTranscriptChange(null);
    setParseResult(null);
    setPendingData(null);
    setFileName(null);
    setUploadError(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  }

  function handleDiscardPreview() {
    setParseResult(null);
    setPendingData(null);
    setFileName(null);
    setUploadError(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = "";
    }
  }

  // ---------------------------------------------------------------------------
  // Render
  // ---------------------------------------------------------------------------

  return (
    <section
      className="rounded-lg border border-gray-200 bg-gray-50 p-4 dark:border-gray-700 dark:bg-gray-800/50"
      aria-labelledby="transcript-editor-heading"
    >
      <div className="mb-3 flex items-center justify-between">
        <h3
          className="text-sm font-medium text-gray-900 dark:text-white"
          id="transcript-editor-heading"
        >
          Transcript
        </h3>

        {/* Status badge */}
        {existingData ? (
          <span className="rounded-full bg-green-100 px-2 py-0.5 text-xs font-medium text-green-800 dark:bg-green-900/40 dark:text-green-300">
            {existingData.cueCount} cues · {formatMs(existingData.durationMs)} ·{" "}
            {existingData.isAutoGenerated ? "Auto" : "Manual"}
          </span>
        ) : (
          <span className="rounded-full bg-gray-200 px-2 py-0.5 text-xs font-medium text-gray-600 dark:bg-gray-700 dark:text-gray-400">
            No transcript
          </span>
        )}
      </div>

      {/* ── Upload area ────────────────────────────────────────────────── */}
      {!pendingData && (
        <div className="space-y-3">
          <div>
            <label
              className="block text-xs font-medium text-gray-700 dark:text-gray-300"
              htmlFor="vtt-upload"
            >
              Upload VTT file
            </label>
            <input
              className="mt-1 block w-full rounded border border-gray-300 bg-white px-3 py-1.5 text-sm text-gray-700 file:mr-3 file:cursor-pointer file:rounded file:border-0 file:bg-green-50 file:px-3 file:py-1 file:text-xs file:font-medium file:text-green-700 hover:file:bg-green-100 focus:border-green-500 focus:ring-1 focus:ring-green-500 focus:outline-none dark:border-gray-600 dark:bg-gray-700 dark:text-gray-300"
              id="vtt-upload"
              ref={fileInputRef}
              type="file"
              accept=".vtt"
              aria-describedby={uploadError ? "vtt-upload-error" : undefined}
              aria-invalid={uploadError ? true : undefined}
              onChange={handleFileChange}
            />
            {uploadError && (
              <p
                className="mt-1 text-xs text-red-600 dark:text-red-400"
                id="vtt-upload-error"
                role="alert"
              >
                {uploadError}
              </p>
            )}
          </div>

          {existingData && (
            <button
              className="text-xs text-red-600 hover:underline dark:text-red-400"
              onClick={handleClear}
              type="button"
            >
              Remove current transcript
            </button>
          )}

          <p className="text-xs text-gray-500 dark:text-gray-400">
            Accepts WebVTT (.vtt) files. Speaker labels via{" "}
            <code className="rounded bg-gray-100 px-1 py-0.5 dark:bg-gray-700">
              &lt;v Name&gt;
            </code>{" "}
            tags are preserved.
          </p>
        </div>
      )}

      {/* ── Parse preview ──────────────────────────────────────────────── */}
      {pendingData && parseResult && (
        <div className="space-y-3">
          {/* Summary */}
          <div className="rounded border border-green-200 bg-white p-3 dark:border-green-800/50 dark:bg-gray-900/50">
            <p className="text-xs font-medium text-gray-700 dark:text-gray-300">
              Parsed: <strong>{pendingData.cueCount} cues</strong> ·{" "}
              <strong>{formatMs(pendingData.durationMs)}</strong> duration ·{" "}
              <strong>{fileName}</strong>
            </p>

            {/* Warnings */}
            {parseResult.warnings.length > 0 && (
              <WarningList warnings={parseResult.warnings} />
            )}
          </div>

          {/* Cue preview (first 5) */}
          <div>
            <p className="mb-1 text-xs font-medium text-gray-600 dark:text-gray-400">
              Preview (first {Math.min(pendingData.cues.length, 5)} cues)
            </p>
            <ol
              className="space-y-1"
              aria-label="Transcript cue preview"
            >
              {pendingData.cues.slice(0, 5).map((cue, idx) => (
                <li
                  className="flex gap-3 rounded bg-white px-2 py-1.5 text-xs dark:bg-gray-900/50"
                  key={`${cue.id}-${idx}`}
                >
                  <span className="shrink-0 font-mono text-gray-400 tabular-nums dark:text-gray-500">
                    {formatCueTime(cue.startMs)}
                  </span>
                  <span className="text-gray-700 dark:text-gray-300">
                    {cue.speaker && (
                      <span className="mr-1 font-medium text-gray-900 dark:text-white">
                        {cue.speaker}:
                      </span>
                    )}
                    {cue.text}
                  </span>
                </li>
              ))}
            </ol>
            {pendingData.cues.length > 5 && (
              <p className="mt-1 text-xs text-gray-500 dark:text-gray-400">
                … and {pendingData.cues.length - 5} more cues.
              </p>
            )}
          </div>

          {/* Apply / Discard */}
          <div className="flex gap-2">
            <button
              className="inline-flex items-center rounded bg-green-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-green-700 focus:ring-2 focus:ring-green-500 focus:ring-offset-1 focus:outline-none disabled:opacity-50"
              onClick={handleApply}
              type="button"
            >
              Apply transcript
            </button>
            <button
              className={cn(
                "inline-flex items-center rounded border border-gray-300 bg-white px-3 py-1.5 text-xs font-medium text-gray-700",
                "hover:bg-gray-50 focus:ring-2 focus:ring-gray-400 focus:ring-offset-1 focus:outline-none",
                "dark:border-gray-600 dark:bg-gray-700 dark:text-gray-300 dark:hover:bg-gray-600",
              )}
              onClick={handleDiscardPreview}
              type="button"
            >
              Discard
            </button>
          </div>
        </div>
      )}
    </section>
  );
}

// ---------------------------------------------------------------------------
// Warning list sub-component
// ---------------------------------------------------------------------------

interface WarningListProps {
  warnings: VttParseWarning[];
}

function WarningList({ warnings }: WarningListProps) {
  const MAX_SHOWN = 5;
  const shown = warnings.slice(0, MAX_SHOWN);
  const extra = warnings.length - MAX_SHOWN;

  return (
    <div
      className="mt-2 rounded border border-amber-200 bg-amber-50 p-2 dark:border-amber-800/50 dark:bg-amber-900/20"
      role="alert"
      aria-label="VTT parse warnings"
    >
      <p className="mb-1 text-xs font-medium text-amber-800 dark:text-amber-300">
        {warnings.length} parse warning{warnings.length !== 1 ? "s" : ""}
      </p>
      <ul className="space-y-0.5">
        {shown.map((w, i) => (
          <li
            className="text-xs text-amber-700 dark:text-amber-400"
            key={i}
          >
            Line {w.line}: {w.message}
          </li>
        ))}
      </ul>
      {extra > 0 && (
        <p className="mt-1 text-xs text-amber-600 dark:text-amber-500">
          … and {extra} more warning{extra !== 1 ? "s" : ""}.
        </p>
      )}
    </div>
  );
}
