/**
 * Tests for TranscriptEditorSection (Phase 2 admin VTT upload).
 *
 * FileReader is mocked so we can trigger onload synchronously in tests
 * without relying on actual DOM file-reading APIs.
 */
import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, describe, expect, it, vi } from "vitest";
import { TranscriptEditorSection } from "~/components/transcript-editor-section";
import type { TranscriptData } from "~/lib/transcript";

// ---------------------------------------------------------------------------
// FileReader mock helpers
// ---------------------------------------------------------------------------

/**
 * Installs a global FileReader stub whose `readAsText` immediately invokes
 * the assigned `onload` callback with the provided text. This allows tests to
 * exercise the full onload → parseVtt → setState flow synchronously.
 */
function mockFileReader(textToReturn: string) {
  // We need a real class so that `new FileReader()` works in the component.
  class MockFileReader {
    onload: ((e: ProgressEvent<FileReader>) => void) | null = null;

    readAsText() {
      if (this.onload) {
        this.onload({
          target: { result: textToReturn },
        } as unknown as ProgressEvent<FileReader>);
      }
    }
  }

  vi.stubGlobal("FileReader", MockFileReader);
}

// ---------------------------------------------------------------------------
// Minimal valid VTT content
// ---------------------------------------------------------------------------

const VALID_VTT = `WEBVTT

00:00:00.000 --> 00:00:03.000
Welcome to the lesson.

00:00:04.000 --> 00:00:07.000
Today we cover Fastify.
`;

const EMPTY_VTT = `WEBVTT

`;

// ---------------------------------------------------------------------------
// A pre-existing valid TranscriptData value (version:1)
// ---------------------------------------------------------------------------

const EXISTING_TRANSCRIPT: TranscriptData = {
  version: 1,
  language: "en",
  source: "manual",
  isAutoGenerated: false,
  cueCount: 2,
  durationMs: 7000,
  cues: [
    { id: "c0", startMs: 0, endMs: 3000, text: "Welcome to the lesson." },
    { id: "c1", startMs: 4000, endMs: 7000, text: "Today we cover Fastify." },
  ],
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeVttFile(content: string, name = "transcript.vtt") {
  return new File([content], name, { type: "text/vtt" });
}

// ---------------------------------------------------------------------------
// Status badge
// ---------------------------------------------------------------------------

describe("TranscriptEditorSection — status badge", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it("shows 'No transcript' badge when currentTranscription is null", () => {
    render(
      <TranscriptEditorSection
        currentTranscription={null}
        onTranscriptChange={vi.fn()}
      />,
    );
    expect(screen.getByText("No transcript")).toBeInTheDocument();
  });

  it("shows 'No transcript' badge when currentTranscription is undefined", () => {
    render(
      <TranscriptEditorSection
        currentTranscription={undefined}
        onTranscriptChange={vi.fn()}
      />,
    );
    expect(screen.getByText("No transcript")).toBeInTheDocument();
  });

  it("shows 'No transcript' badge for an invalid shape", () => {
    render(
      <TranscriptEditorSection
        currentTranscription={{ segments: [] }}
        onTranscriptChange={vi.fn()}
      />,
    );
    expect(screen.getByText("No transcript")).toBeInTheDocument();
  });

  it("shows cue count, duration, and source badge for existing transcript", () => {
    render(
      <TranscriptEditorSection
        currentTranscription={EXISTING_TRANSCRIPT}
        onTranscriptChange={vi.fn()}
      />,
    );
    // Badge text: "2 cues · 0:07 · Manual"
    expect(screen.getByText(/2 cues/)).toBeInTheDocument();
    expect(screen.getByText(/Manual/)).toBeInTheDocument();
  });

  it("shows 'Auto' in badge for an auto-generated transcript", () => {
    const autoTranscript: TranscriptData = {
      ...EXISTING_TRANSCRIPT,
      source: "auto",
      isAutoGenerated: true,
    };
    render(
      <TranscriptEditorSection
        currentTranscription={autoTranscript}
        onTranscriptChange={vi.fn()}
      />,
    );
    expect(screen.getByText(/Auto/)).toBeInTheDocument();
  });
});

// ---------------------------------------------------------------------------
// File input
// ---------------------------------------------------------------------------

describe("TranscriptEditorSection — file input", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it("renders a file upload input accepting .vtt", () => {
    render(
      <TranscriptEditorSection
        currentTranscription={null}
        onTranscriptChange={vi.fn()}
      />,
    );
    const input = screen.getByLabelText("Upload VTT file");
    expect(input).toBeInTheDocument();
    expect(input).toHaveAttribute("accept", ".vtt");
  });

  it("shows an error when a non-VTT file is selected", async () => {
    // Use applyAccept: false so userEvent.upload does not filter out the
    // non-.vtt file — the component itself handles the type check and shows
    // the error message.
    const user = userEvent.setup({ applyAccept: false });
    render(
      <TranscriptEditorSection
        currentTranscription={null}
        onTranscriptChange={vi.fn()}
      />,
    );
    const input = screen.getByLabelText("Upload VTT file");
    const badFile = new File(["content"], "transcript.txt", {
      type: "text/plain",
    });
    await user.upload(input, badFile);

    await waitFor(() => {
      expect(
        screen.getByText("Only .vtt files are supported."),
      ).toBeInTheDocument();
    });
  });

  it("shows the parse error when VTT has no valid cues", async () => {
    mockFileReader(EMPTY_VTT);
    const user = userEvent.setup();
    render(
      <TranscriptEditorSection
        currentTranscription={null}
        onTranscriptChange={vi.fn()}
      />,
    );
    const input = screen.getByLabelText("Upload VTT file");
    await user.upload(input, makeVttFile(EMPTY_VTT));

    await waitFor(() => {
      expect(
        screen.getByText("No valid cues were found in this VTT file."),
      ).toBeInTheDocument();
    });
  });
});

// ---------------------------------------------------------------------------
// Parse preview
// ---------------------------------------------------------------------------

describe("TranscriptEditorSection — parse preview", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it("shows cue preview after uploading a valid VTT file", async () => {
    mockFileReader(VALID_VTT);
    const user = userEvent.setup();
    render(
      <TranscriptEditorSection
        currentTranscription={null}
        onTranscriptChange={vi.fn()}
      />,
    );
    const input = screen.getByLabelText("Upload VTT file");
    await user.upload(input, makeVttFile(VALID_VTT));

    // The parsed summary paragraph (strong tag) shows cue count
    await waitFor(() => {
      expect(
        screen.getByRole("list", { name: "Transcript cue preview" }),
      ).toBeInTheDocument();
    });
    // First cue text visible in preview
    expect(screen.getByText("Welcome to the lesson.")).toBeInTheDocument();
  });

  it("shows 'Apply transcript' and 'Discard' buttons after a valid upload", async () => {
    mockFileReader(VALID_VTT);
    const user = userEvent.setup();
    render(
      <TranscriptEditorSection
        currentTranscription={null}
        onTranscriptChange={vi.fn()}
      />,
    );
    await user.upload(
      screen.getByLabelText("Upload VTT file"),
      makeVttFile(VALID_VTT),
    );

    await waitFor(() => {
      expect(
        screen.getByRole("button", { name: "Apply transcript" }),
      ).toBeInTheDocument();
    });
    expect(screen.getByRole("button", { name: "Discard" })).toBeInTheDocument();
  });

  it("calls onTranscriptChange with TranscriptData when Apply is clicked", async () => {
    mockFileReader(VALID_VTT);
    const user = userEvent.setup();
    const onTranscriptChange = vi.fn();
    render(
      <TranscriptEditorSection
        currentTranscription={null}
        onTranscriptChange={onTranscriptChange}
      />,
    );
    await user.upload(
      screen.getByLabelText("Upload VTT file"),
      makeVttFile(VALID_VTT),
    );

    await waitFor(() =>
      screen.getByRole("button", { name: "Apply transcript" }),
    );
    await user.click(screen.getByRole("button", { name: "Apply transcript" }));

    await waitFor(() => {
      expect(onTranscriptChange).toHaveBeenCalledOnce();
      const arg = onTranscriptChange.mock.calls[0][0];
      expect(arg).not.toBeNull();
      expect(arg.version).toBe(1);
      expect(arg.cueCount).toBe(2);
    });
  });

  it("removes the preview when Discard is clicked", async () => {
    mockFileReader(VALID_VTT);
    const user = userEvent.setup();
    render(
      <TranscriptEditorSection
        currentTranscription={null}
        onTranscriptChange={vi.fn()}
      />,
    );
    await user.upload(
      screen.getByLabelText("Upload VTT file"),
      makeVttFile(VALID_VTT),
    );

    await waitFor(() =>
      screen.getByRole("button", { name: "Apply transcript" }),
    );
    await user.click(screen.getByRole("button", { name: "Discard" }));

    await waitFor(() => {
      expect(
        screen.queryByRole("button", { name: "Apply transcript" }),
      ).not.toBeInTheDocument();
    });
    // Upload input should be visible again
    expect(screen.getByLabelText("Upload VTT file")).toBeInTheDocument();
  });
});

// ---------------------------------------------------------------------------
// Remove existing transcript
// ---------------------------------------------------------------------------

describe("TranscriptEditorSection — remove existing transcript", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it("shows 'Remove current transcript' button when transcript exists", () => {
    render(
      <TranscriptEditorSection
        currentTranscription={EXISTING_TRANSCRIPT}
        onTranscriptChange={vi.fn()}
      />,
    );
    expect(
      screen.getByRole("button", { name: "Remove current transcript" }),
    ).toBeInTheDocument();
  });

  it("does not show 'Remove' button when no transcript exists", () => {
    render(
      <TranscriptEditorSection
        currentTranscription={null}
        onTranscriptChange={vi.fn()}
      />,
    );
    expect(
      screen.queryByRole("button", { name: "Remove current transcript" }),
    ).not.toBeInTheDocument();
  });

  it("calls onTranscriptChange(null) when Remove is clicked", async () => {
    const user = userEvent.setup();
    const onTranscriptChange = vi.fn();
    render(
      <TranscriptEditorSection
        currentTranscription={EXISTING_TRANSCRIPT}
        onTranscriptChange={onTranscriptChange}
      />,
    );

    await user.click(
      screen.getByRole("button", { name: "Remove current transcript" }),
    );

    expect(onTranscriptChange).toHaveBeenCalledOnce();
    expect(onTranscriptChange).toHaveBeenCalledWith(null);
  });
});

// ---------------------------------------------------------------------------
// Section heading and landmark
// ---------------------------------------------------------------------------

describe("TranscriptEditorSection — structure and accessibility", () => {
  it("renders a section with the heading 'Transcript'", () => {
    render(
      <TranscriptEditorSection
        currentTranscription={null}
        onTranscriptChange={vi.fn()}
      />,
    );
    expect(
      screen.getByRole("region", { name: "Transcript" }),
    ).toBeInTheDocument();
    expect(
      screen.getByRole("heading", { name: "Transcript" }),
    ).toBeInTheDocument();
  });
});
