import { render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it } from "vitest";
import { TranscriptPanel } from "~/components/transcript-panel";
import type { TranscriptData } from "~/lib/transcript";

// ---------------------------------------------------------------------------
// Test data
// ---------------------------------------------------------------------------

const VALID_TRANSCRIPT: TranscriptData = {
  version: 1,
  language: "en",
  source: "manual",
  isAutoGenerated: false,
  cueCount: 3,
  durationMs: 10_000,
  cues: [
    { id: "c0", startMs: 0, endMs: 3000, text: "Welcome to the lesson." },
    {
      id: "c1",
      startMs: 4000,
      endMs: 7000,
      text: "Today we cover Fastify.",
    },
    {
      id: "c2",
      startMs: 8000,
      endMs: 10000,
      text: "Let's build an API.",
    },
  ],
};

const AUTO_TRANSCRIPT: TranscriptData = {
  ...VALID_TRANSCRIPT,
  source: "auto",
  isAutoGenerated: true,
};

const MULTI_SPEAKER_TRANSCRIPT: TranscriptData = {
  version: 1,
  language: "en",
  source: "manual",
  isAutoGenerated: false,
  cueCount: 2,
  durationMs: 6000,
  cues: [
    {
      id: "c0",
      startMs: 0,
      endMs: 3000,
      text: "Good morning.",
      speaker: "Alice",
    },
    {
      id: "c1",
      startMs: 3000,
      endMs: 6000,
      text: "Good morning Alice.",
      speaker: "Bob",
    },
  ],
};

// ---------------------------------------------------------------------------
// Empty / invalid states
// ---------------------------------------------------------------------------

describe("TranscriptPanel — empty and invalid states", () => {
  it("shows no-transcript message when transcription is null", async () => {
    render(
      <TranscriptPanel
        transcription={null}
        hasVideo={true}
      />,
    );
    expect(await screen.findByRole("status")).toBeInTheDocument();
  });

  it("shows no-transcript message when transcription is undefined", async () => {
    render(
      <TranscriptPanel
        transcription={undefined}
        hasVideo={true}
      />,
    );
    expect(await screen.findByRole("status")).toBeInTheDocument();
  });

  it("shows invalid-schema message for old-format segments payload", async () => {
    const old = { segments: [{ start: 0, end: 10, text: "Hi" }] };
    render(
      <TranscriptPanel
        transcription={old}
        hasVideo={true}
      />,
    );
    expect(await screen.findByRole("status")).toBeInTheDocument();
  });

  it("shows no-cues message for a transcript with empty cue array", async () => {
    const empty: TranscriptData = {
      ...VALID_TRANSCRIPT,
      cues: [],
      cueCount: 0,
      durationMs: 0,
    };
    render(
      <TranscriptPanel
        transcription={empty}
        hasVideo={true}
      />,
    );
    expect(await screen.findByRole("status")).toBeInTheDocument();
  });

  it("is always eligible when hasVideo is false, even with no transcript", async () => {
    // Non-video lesson with no transcript → still renders the panel but the
    // eligibility check for non-video lessons always passes, so validateTranscriptData
    // returns null → fallback empty message.
    render(
      <TranscriptPanel
        transcription={null}
        hasVideo={false}
      />,
    );
    expect(await screen.findByRole("status")).toBeInTheDocument();
  });
});

// ---------------------------------------------------------------------------
// Timestamp mode (default)
// ---------------------------------------------------------------------------

describe("TranscriptPanel — timestamp mode", () => {
  it("renders the transcript panel with cue list", async () => {
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    expect(
      await screen.findByRole("region", { name: "Lesson transcript" }),
    ).toBeInTheDocument();
    expect(
      screen.getByRole("list", { name: "Transcript cues" }),
    ).toBeInTheDocument();
  });

  it("renders one list item per cue", async () => {
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    const cueList = await screen.findByRole("list", {
      name: "Transcript cues",
    });
    const cues = within(cueList).getAllByRole("listitem");
    expect(cues).toHaveLength(3);
  });

  it("renders cue timestamps", async () => {
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("list", { name: "Transcript cues" });
    // First cue starts at 0ms → "0:00"
    expect(screen.getByLabelText("Time: 0:00")).toBeInTheDocument();
    // Second cue starts at 4000ms → "0:04"
    expect(screen.getByLabelText("Time: 0:04")).toBeInTheDocument();
  });

  it("renders cue text content", async () => {
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("list", { name: "Transcript cues" });
    expect(screen.getByText("Welcome to the lesson.")).toBeInTheDocument();
    expect(screen.getByText("Today we cover Fastify.")).toBeInTheDocument();
    expect(screen.getByText("Let's build an API.")).toBeInTheDocument();
  });

  it("shows 'Manual' source badge for manual transcripts", async () => {
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });
    expect(screen.getByText("Manual")).toBeInTheDocument();
  });

  it("shows 'Auto' source badge for auto-generated transcripts", async () => {
    render(<TranscriptPanel transcription={AUTO_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });
    expect(screen.getByText("Auto")).toBeInTheDocument();
  });

  it("renders speaker labels when present", async () => {
    render(<TranscriptPanel transcription={MULTI_SPEAKER_TRANSCRIPT} />);
    await screen.findByRole("list", { name: "Transcript cues" });
    expect(screen.getByText("Alice:")).toBeInTheDocument();
    expect(screen.getByText("Bob:")).toBeInTheDocument();
  });
});

// ---------------------------------------------------------------------------
// Paragraph mode
// ---------------------------------------------------------------------------

describe("TranscriptPanel — paragraph mode", () => {
  it("switches to paragraph mode on button click", async () => {
    const user = userEvent.setup();
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });

    await user.click(screen.getByRole("button", { name: "Paragraph" }));

    expect(
      screen.getByRole("list", { name: "Transcript paragraphs" }),
    ).toBeInTheDocument();
    expect(
      screen.queryByRole("list", { name: "Transcript cues" }),
    ).not.toBeInTheDocument();
  });

  it("renders at least one paragraph element in paragraph mode", async () => {
    const user = userEvent.setup();
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });

    await user.click(screen.getByRole("button", { name: "Paragraph" }));

    const paraList = screen.getByRole("list", {
      name: "Transcript paragraphs",
    });
    const paras = within(paraList).getAllByRole("listitem");
    expect(paras.length).toBeGreaterThan(0);
  });

  it("contains transcript text content in paragraph mode", async () => {
    const user = userEvent.setup();
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });

    await user.click(screen.getByRole("button", { name: "Paragraph" }));

    // All cue text should appear somewhere in the paragraph list
    expect(screen.getByText(/Welcome to the lesson/)).toBeInTheDocument();
  });

  it("switches back to timestamp mode from paragraph mode", async () => {
    const user = userEvent.setup();
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });

    await user.click(screen.getByRole("button", { name: "Paragraph" }));
    await user.click(screen.getByRole("button", { name: "Timestamps" }));

    expect(
      screen.getByRole("list", { name: "Transcript cues" }),
    ).toBeInTheDocument();
    expect(
      screen.queryByRole("list", { name: "Transcript paragraphs" }),
    ).not.toBeInTheDocument();
  });
});

// ---------------------------------------------------------------------------
// Mode toggle button state
// ---------------------------------------------------------------------------

describe("TranscriptPanel — mode toggle accessibility", () => {
  it("marks timestamp button as pressed by default", async () => {
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });

    expect(screen.getByRole("button", { name: "Timestamps" })).toHaveAttribute(
      "aria-pressed",
      "true",
    );
    expect(screen.getByRole("button", { name: "Paragraph" })).toHaveAttribute(
      "aria-pressed",
      "false",
    );
  });

  it("updates aria-pressed after switching to paragraph mode", async () => {
    const user = userEvent.setup();
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });

    await user.click(screen.getByRole("button", { name: "Paragraph" }));

    expect(screen.getByRole("button", { name: "Paragraph" })).toHaveAttribute(
      "aria-pressed",
      "true",
    );
    expect(screen.getByRole("button", { name: "Timestamps" })).toHaveAttribute(
      "aria-pressed",
      "false",
    );
  });
});
