/**
 * Phase 3 tests for TranscriptPanel:
 *   - onSeek callback on cue click
 *   - Active cue highlighting driven by currentTimeSeconds
 *   - Follow-playback toggle
 *   - Inline search (open, type, match counter, prev/next, keyboard shortcuts, close)
 */
import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { TranscriptPanel } from "~/components/transcript-panel";
import type { TranscriptData } from "~/lib/transcript";

// ---------------------------------------------------------------------------
// Stub scrollIntoView — JSDOM does not implement it
// ---------------------------------------------------------------------------

beforeEach(() => {
  Object.defineProperty(Element.prototype, "scrollIntoView", {
    writable: true,
    configurable: true,
    value: vi.fn(),
  });
});

// ---------------------------------------------------------------------------
// Test data
// ---------------------------------------------------------------------------

const VALID_TRANSCRIPT: TranscriptData = {
  version: 1,
  language: "en",
  source: "manual",
  isAutoGenerated: false,
  cueCount: 4,
  durationMs: 16_000,
  cues: [
    { id: "c0", startMs: 0, endMs: 3000, text: "Welcome to the lesson." },
    { id: "c1", startMs: 4000, endMs: 7000, text: "Today we cover Fastify." },
    { id: "c2", startMs: 8000, endMs: 11000, text: "Fastify is very fast." },
    { id: "c3", startMs: 12000, endMs: 15000, text: "Let's build an API." },
  ],
};

// ---------------------------------------------------------------------------
// onSeek — cue click
// ---------------------------------------------------------------------------

describe("TranscriptPanel — onSeek on cue click", () => {
  it("calls onSeek with startMs/1000 when a cue row is clicked", async () => {
    const user = userEvent.setup();
    const onSeek = vi.fn();
    render(
      <TranscriptPanel
        transcription={VALID_TRANSCRIPT}
        onSeek={onSeek}
      />,
    );

    // Cue rows become role="button" when onSeek is provided
    const cueButtons = await screen.findAllByRole("button", {
      name: /Time:/,
    });
    // Wait for the cue list
    expect(cueButtons.length).toBeGreaterThan(0);

    // Click the second cue (startMs 4000 → 4 seconds)
    const cueList = screen.getByRole("list", { name: "Transcript cues" });
    const listItems = cueList.querySelectorAll("li");
    await user.click(listItems[1]);

    expect(onSeek).toHaveBeenCalledWith(4);
  });

  it("does not render cue rows as buttons when onSeek is not provided", async () => {
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("list", { name: "Transcript cues" });
    // Without onSeek no li has role="button"
    const cueList = screen.getByRole("list", { name: "Transcript cues" });
    const buttonItems = cueList.querySelectorAll("li[role='button']");
    expect(buttonItems).toHaveLength(0);
  });

  it("calls onSeek with paragraph startMs/1000 when a paragraph is clicked", async () => {
    const user = userEvent.setup();
    const onSeek = vi.fn();
    render(
      <TranscriptPanel
        transcription={VALID_TRANSCRIPT}
        onSeek={onSeek}
      />,
    );
    await screen.findByRole("region", { name: "Lesson transcript" });

    // Switch to paragraph mode
    await user.click(screen.getByRole("button", { name: "Paragraph" }));

    const paraList = screen.getByRole("list", {
      name: "Transcript paragraphs",
    });
    const paras = paraList.querySelectorAll("li");
    await user.click(paras[0]);

    expect(onSeek).toHaveBeenCalled();
    // First paragraph starts at cue 0 → 0s
    expect(onSeek).toHaveBeenCalledWith(0);
  });
});

// ---------------------------------------------------------------------------
// Active cue highlight
// ---------------------------------------------------------------------------

describe("TranscriptPanel — active cue highlight", () => {
  it("marks the cue covering currentTimeSeconds as aria-current", async () => {
    // Cue c1 covers 4000–7000 ms; passing 5s should make it active
    render(
      <TranscriptPanel
        transcription={VALID_TRANSCRIPT}
        currentTimeSeconds={5}
      />,
    );
    await screen.findByRole("list", { name: "Transcript cues" });
    const cueList = screen.getByRole("list", { name: "Transcript cues" });
    const activeItems = cueList.querySelectorAll("[aria-current='true']");
    expect(activeItems).toHaveLength(1);
  });

  it("marks no cue as active when currentTimeSeconds is outside all cues", async () => {
    render(
      <TranscriptPanel
        transcription={VALID_TRANSCRIPT}
        currentTimeSeconds={999}
      />,
    );
    await screen.findByRole("list", { name: "Transcript cues" });
    const cueList = screen.getByRole("list", { name: "Transcript cues" });
    const activeItems = cueList.querySelectorAll("[aria-current='true']");
    expect(activeItems).toHaveLength(0);
  });
});

// ---------------------------------------------------------------------------
// Follow-playback toggle
// ---------------------------------------------------------------------------

describe("TranscriptPanel — follow-playback toggle", () => {
  it("renders the Follow button in timestamp mode", async () => {
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });
    expect(screen.getByRole("button", { name: "Follow" })).toBeInTheDocument();
  });

  it("Follow button is aria-pressed=true by default", async () => {
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });
    expect(screen.getByRole("button", { name: "Follow" })).toHaveAttribute(
      "aria-pressed",
      "true",
    );
  });

  it("toggles aria-pressed when Follow is clicked", async () => {
    const user = userEvent.setup();
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });

    const followBtn = screen.getByRole("button", { name: "Follow" });
    await user.click(followBtn);

    expect(followBtn).toHaveAttribute("aria-pressed", "false");
  });

  it("does not render Follow button in paragraph mode", async () => {
    const user = userEvent.setup();
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });

    await user.click(screen.getByRole("button", { name: "Paragraph" }));
    expect(
      screen.queryByRole("button", { name: "Follow" }),
    ).not.toBeInTheDocument();
  });

  it("clicking a cue disables follow-playback (aria-pressed becomes false)", async () => {
    const user = userEvent.setup();
    const onSeek = vi.fn();
    render(
      <TranscriptPanel
        transcription={VALID_TRANSCRIPT}
        onSeek={onSeek}
      />,
    );
    await screen.findByRole("region", { name: "Lesson transcript" });

    // Follow starts ON
    const followBtn = screen.getByRole("button", { name: "Follow" });
    expect(followBtn).toHaveAttribute("aria-pressed", "true");

    // Click first cue
    const cueList = screen.getByRole("list", { name: "Transcript cues" });
    const firstItem = cueList.querySelectorAll("li")[0];
    await user.click(firstItem);

    // Follow should be turned OFF automatically
    await waitFor(() => {
      expect(followBtn).toHaveAttribute("aria-pressed", "false");
    });
  });
});

// ---------------------------------------------------------------------------
// Search
// ---------------------------------------------------------------------------

describe("TranscriptPanel — search", () => {
  it("renders a Search toggle button", async () => {
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });
    expect(
      screen.getByRole("button", { name: "Toggle transcript search" }),
    ).toBeInTheDocument();
  });

  it("opens the search bar when Search is clicked", async () => {
    const user = userEvent.setup();
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });

    await user.click(
      screen.getByRole("button", { name: "Toggle transcript search" }),
    );

    expect(
      screen.getByRole("searchbox", { name: "Transcript search query" }),
    ).toBeInTheDocument();
  });

  it("shows match counter after typing a search query", async () => {
    const user = userEvent.setup();
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });

    await user.click(
      screen.getByRole("button", { name: "Toggle transcript search" }),
    );
    const input = screen.getByRole("searchbox", {
      name: "Transcript search query",
    });
    // "Fastify" appears in cues c1 and c2
    await user.type(input, "Fastify");

    await waitFor(() => {
      expect(screen.getByText(/1 \/ 2/)).toBeInTheDocument();
    });
  });

  it("shows '0 results' when query has no matches", async () => {
    const user = userEvent.setup();
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });

    await user.click(
      screen.getByRole("button", { name: "Toggle transcript search" }),
    );
    await user.type(
      screen.getByRole("searchbox", { name: "Transcript search query" }),
      "xyzxyz",
    );

    await waitFor(() => {
      expect(screen.getByText("0 results")).toBeInTheDocument();
    });
  });

  it("advances to next match on Next button click", async () => {
    const user = userEvent.setup();
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });

    await user.click(
      screen.getByRole("button", { name: "Toggle transcript search" }),
    );
    await user.type(
      screen.getByRole("searchbox", { name: "Transcript search query" }),
      "Fastify",
    );

    // Initially at 1/2
    await waitFor(() => expect(screen.getByText(/1 \/ 2/)).toBeInTheDocument());

    await user.click(screen.getByRole("button", { name: "Next match" }));
    await waitFor(() => expect(screen.getByText(/2 \/ 2/)).toBeInTheDocument());
  });

  it("goes to previous match on Prev button click", async () => {
    const user = userEvent.setup();
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });

    await user.click(
      screen.getByRole("button", { name: "Toggle transcript search" }),
    );
    await user.type(
      screen.getByRole("searchbox", { name: "Transcript search query" }),
      "Fastify",
    );

    // advance to 2/2 first
    await waitFor(() => expect(screen.getByText(/1 \/ 2/)).toBeInTheDocument());
    await user.click(screen.getByRole("button", { name: "Next match" }));
    await waitFor(() => expect(screen.getByText(/2 \/ 2/)).toBeInTheDocument());

    // go back
    await user.click(screen.getByRole("button", { name: "Previous match" }));
    await waitFor(() => expect(screen.getByText(/1 \/ 2/)).toBeInTheDocument());
  });

  it("advances with Enter key and goes back with Shift+Enter", async () => {
    const user = userEvent.setup();
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });

    await user.click(
      screen.getByRole("button", { name: "Toggle transcript search" }),
    );
    const input = screen.getByRole("searchbox", {
      name: "Transcript search query",
    });
    await user.type(input, "Fastify");
    await waitFor(() => expect(screen.getByText(/1 \/ 2/)).toBeInTheDocument());

    // Enter → next match
    await user.keyboard("{Enter}");
    await waitFor(() => expect(screen.getByText(/2 \/ 2/)).toBeInTheDocument());

    // Shift+Enter → previous match
    await user.keyboard("{Shift>}{Enter}{/Shift}");
    await waitFor(() => expect(screen.getByText(/1 \/ 2/)).toBeInTheDocument());
  });

  it("closes search bar on Escape key", async () => {
    const user = userEvent.setup();
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });

    await user.click(
      screen.getByRole("button", { name: "Toggle transcript search" }),
    );
    // Verify the search box opened, then close it with Escape
    expect(
      screen.getByRole("searchbox", { name: "Transcript search query" }),
    ).toBeInTheDocument();

    await user.keyboard("{Escape}");

    await waitFor(() => {
      expect(
        screen.queryByRole("searchbox", { name: "Transcript search query" }),
      ).not.toBeInTheDocument();
    });
  });

  it("closes search bar on Close search button click", async () => {
    const user = userEvent.setup();
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });

    await user.click(
      screen.getByRole("button", { name: "Toggle transcript search" }),
    );
    expect(
      screen.getByRole("searchbox", { name: "Transcript search query" }),
    ).toBeInTheDocument();

    await user.click(screen.getByRole("button", { name: "Close search" }));

    await waitFor(() => {
      expect(
        screen.queryByRole("searchbox", { name: "Transcript search query" }),
      ).not.toBeInTheDocument();
    });
  });

  it("prev/next buttons are disabled when there are no matches", async () => {
    const user = userEvent.setup();
    render(<TranscriptPanel transcription={VALID_TRANSCRIPT} />);
    await screen.findByRole("region", { name: "Lesson transcript" });

    await user.click(
      screen.getByRole("button", { name: "Toggle transcript search" }),
    );

    // No query yet — match count is 0
    expect(
      screen.getByRole("button", { name: "Previous match" }),
    ).toBeDisabled();
    expect(screen.getByRole("button", { name: "Next match" })).toBeDisabled();
  });

  it("calls onSeek when the Next button advances to a match with onSeek provided", async () => {
    const user = userEvent.setup();
    const onSeek = vi.fn();
    render(
      <TranscriptPanel
        transcription={VALID_TRANSCRIPT}
        onSeek={onSeek}
      />,
    );
    await screen.findByRole("region", { name: "Lesson transcript" });

    await user.click(
      screen.getByRole("button", { name: "Toggle transcript search" }),
    );
    await user.type(
      screen.getByRole("searchbox", { name: "Transcript search query" }),
      "Fastify",
    );
    await waitFor(() => expect(screen.getByText(/1 \/ 2/)).toBeInTheDocument());

    await user.click(screen.getByRole("button", { name: "Next match" }));

    // Second "Fastify" cue starts at 8000 ms → 8s
    await waitFor(() => {
      expect(onSeek).toHaveBeenCalledWith(8);
    });
  });
});
