import {
  checkCoursePublishReadiness,
  getAllCourseProgressAsAdmin,
  getCourseProgress,
  getEnrollmentStatus,
  getLessonProgress,
} from "../queries.js";
import { beforeEach, describe, expect, test, vi } from "vitest";

// Hoisted mock for the courseLesson prepared-statement execute so individual
// tests can control the lesson data returned by getLessonsByCourseId.
const { mockLessonFindManyExecute } = vi.hoisted(() => ({
  mockLessonFindManyExecute: vi.fn().mockResolvedValue([]),
}));

// Mock dependencies
vi.mock("~/db/index.js", () => ({
  db: {
    query: {
      course: {
        findMany: vi.fn().mockReturnValue({
          prepare: () => ({
            execute: vi.fn().mockResolvedValue([]),
          }),
        }),
        findFirst: vi.fn().mockReturnValue({
          prepare: () => ({
            execute: vi.fn().mockResolvedValue(null),
          }),
        }),
      },
      courseLesson: {
        findFirst: vi.fn().mockReturnValue({
          prepare: () => ({
            execute: vi.fn().mockResolvedValue(null),
          }),
        }),
        findMany: vi.fn().mockReturnValue({
          prepare: () => ({
            execute: mockLessonFindManyExecute,
          }),
        }),
      },
      lessonProgress: {
        findFirst: vi.fn(),
      },
      courseProgress: {
        findMany: vi.fn().mockReturnValue({
          prepare: () => ({
            execute: vi.fn().mockResolvedValue([]),
          }),
        }),
        findFirst: vi.fn(),
      },
      enrollment: {
        findFirst: vi.fn(),
      },
    },
  },
}));

describe("getCourseProgress", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  test("is a function that accepts userId and courseId", () => {
    expect(typeof getCourseProgress).toBe("function");
  });
});

describe("getLessonProgress", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  test("is a function that accepts userId and lessonId", () => {
    expect(typeof getLessonProgress).toBe("function");
  });
});

describe("getEnrollmentStatus", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  test("is a function that accepts userId and courseId", () => {
    expect(typeof getEnrollmentStatus).toBe("function");
  });
});

describe("getAllCourseProgressAsAdmin", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  test("is an exported function", () => {
    expect(typeof getAllCourseProgressAsAdmin).toBe("function");
  });

  test("returns an array", async () => {
    const result = await getAllCourseProgressAsAdmin();
    expect(Array.isArray(result)).toBe(true);
  });
});

describe("checkCoursePublishReadiness", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    // Restore default: empty lesson list
    mockLessonFindManyExecute.mockResolvedValue([]);
  });

  test("is an exported function", () => {
    expect(typeof checkCoursePublishReadiness).toBe("function");
  });

  test("returns ready:true when course has no lessons", async () => {
    const result = await checkCoursePublishReadiness("course-1");
    expect(result).toEqual({ ready: true, issues: [] });
  });

  test("returns ready:true when all lessons are non-video (exempt)", async () => {
    mockLessonFindManyExecute.mockResolvedValueOnce([
      { id: "l1", title: "Text Only", videoUrl: null, transcription: null },
      { id: "l2", title: "Article", videoUrl: "", transcription: null },
    ]);

    const result = await checkCoursePublishReadiness("course-1");
    expect(result).toEqual({ ready: true, issues: [] });
  });

  test("returns ready:true when video lesson has valid transcript with cues", async () => {
    mockLessonFindManyExecute.mockResolvedValueOnce([
      {
        id: "l1",
        title: "Video Lesson",
        videoUrl: "https://example.com/video.mp4",
        transcription: {
          version: 1,
          language: "en",
          source: "manual",
          isAutoGenerated: false,
          cueCount: 1,
          durationMs: 5000,
          cues: [{ id: "c1", startMs: 0, endMs: 5000, text: "Hello" }],
        },
      },
    ]);

    const result = await checkCoursePublishReadiness("course-1");
    expect(result).toEqual({ ready: true, issues: [] });
  });

  test("returns missing issue for video lesson with null transcript", async () => {
    mockLessonFindManyExecute.mockResolvedValueOnce([
      {
        id: "l1",
        title: "Missing Transcript",
        videoUrl: "https://example.com/video.mp4",
        transcription: null,
      },
    ]);

    const result = await checkCoursePublishReadiness("course-1");
    expect(result.ready).toBe(false);
    expect(result.issues).toEqual([
      {
        lessonId: "l1",
        lessonTitle: "Missing Transcript",
        reason: "missing",
      },
    ]);
  });

  test("returns invalid_schema issue for video lesson with malformed transcript", async () => {
    mockLessonFindManyExecute.mockResolvedValueOnce([
      {
        id: "l2",
        title: "Bad Schema",
        videoUrl: "https://example.com/video.mp4",
        transcription: { segments: [] },
      },
    ]);

    const result = await checkCoursePublishReadiness("course-1");
    expect(result.ready).toBe(false);
    expect(result.issues).toEqual([
      {
        lessonId: "l2",
        lessonTitle: "Bad Schema",
        reason: "invalid_schema",
      },
    ]);
  });

  test("returns no_cues issue for video lesson with empty cues array", async () => {
    mockLessonFindManyExecute.mockResolvedValueOnce([
      {
        id: "l3",
        title: "Empty Cues",
        videoUrl: "https://example.com/video.mp4",
        transcription: {
          version: 1,
          language: "en",
          source: "manual",
          isAutoGenerated: false,
          cueCount: 0,
          durationMs: 0,
          cues: [],
        },
      },
    ]);

    const result = await checkCoursePublishReadiness("course-1");
    expect(result.ready).toBe(false);
    expect(result.issues).toEqual([
      {
        lessonId: "l3",
        lessonTitle: "Empty Cues",
        reason: "no_cues",
      },
    ]);
  });

  test("exempts non-video lessons and flags only video lessons with issues", async () => {
    mockLessonFindManyExecute.mockResolvedValueOnce([
      { id: "l1", title: "Text Lesson", videoUrl: null, transcription: null },
      {
        id: "l2",
        title: "Valid Video",
        videoUrl: "https://example.com/v1.mp4",
        transcription: {
          version: 1,
          language: "en",
          source: "manual",
          isAutoGenerated: false,
          cueCount: 1,
          durationMs: 5000,
          cues: [{ id: "c1", startMs: 0, endMs: 5000, text: "Hello" }],
        },
      },
      {
        id: "l3",
        title: "No Transcript Video",
        videoUrl: "https://example.com/v2.mp4",
        transcription: null,
      },
    ]);

    const result = await checkCoursePublishReadiness("course-1");
    expect(result.ready).toBe(false);
    expect(result.issues).toHaveLength(1);
    expect(result.issues[0]).toEqual({
      lessonId: "l3",
      lessonTitle: "No Transcript Video",
      reason: "missing",
    });
  });

  test("reports multiple issues across different ineligibility reasons", async () => {
    mockLessonFindManyExecute.mockResolvedValueOnce([
      {
        id: "l1",
        title: "No Transcript",
        videoUrl: "https://example.com/v1.mp4",
        transcription: null,
      },
      {
        id: "l2",
        title: "Malformed Data",
        videoUrl: "https://example.com/v2.mp4",
        transcription: { segments: [] },
      },
      {
        id: "l3",
        title: "Zero Cues",
        videoUrl: "https://example.com/v3.mp4",
        transcription: {
          version: 1,
          language: "en",
          source: "manual",
          isAutoGenerated: false,
          cueCount: 0,
          durationMs: 0,
          cues: [],
        },
      },
    ]);

    const result = await checkCoursePublishReadiness("course-1");
    expect(result.ready).toBe(false);
    expect(result.issues).toHaveLength(3);
    expect(result.issues).toEqual([
      { lessonId: "l1", lessonTitle: "No Transcript", reason: "missing" },
      {
        lessonId: "l2",
        lessonTitle: "Malformed Data",
        reason: "invalid_schema",
      },
      { lessonId: "l3", lessonTitle: "Zero Cues", reason: "no_cues" },
    ]);
  });
});
