/**
 * Lesson Transcript E2E Tests — Phase 1
 *
 * Verifies that:
 *   - The lesson page shows a Transcription tab in fullscreen mode.
 *   - A lesson with a valid Phase 1 transcript displays cues in timestamp mode.
 *   - Switching to paragraph mode renders paragraph content (including multiple
 *     paragraphs when speaker changes / large gaps are present).
 *   - A lesson with no valid transcript shows an empty-state message.
 *   - A lesson with an empty cues array shows the "empty" state message.
 *   - An auto-generated transcript shows the "Auto" source badge.
 *   - Cues with a start time > 1 hour render in H:MM:SS format.
 *
 * Uses deterministic fixture IDs seeded by the CI pipeline.
 */

/** Milliseconds to wait for the lesson page to fully load. */
const LESSON_LOAD_TIMEOUT = 15000;

/** Fixture IDs for the "What is Fastify?" preview lesson (Phase 1 transcript).
 *  Transcript has 5 cues: c0–c1 (Alice), c2–c3 (Bob), c4 at 1 h (Alice).
 *  Speaker change between c1→c2 + large gap before c4 produce 3 paragraphs. */
const TRANSCRIPT_LESSON = {
  courseId: "course:01TESTCOURSE00000000001",
  lessonId: "lesson:01TESTLESSON0000000001",
  url: "/courses/course%3A01TESTCOURSE00000000001/lessons/lesson%3A01TESTLESSON0000000001",
};

/**
 * Lesson 2 has `transcription: { segments: [] }` (old-format, empty segments).
 * This triggers the `invalid_schema` reason and renders the empty-state UI.
 */
const NO_TRANSCRIPT_LESSON = {
  courseId: "course:01TESTCOURSE00000000001",
  lessonId: "lesson:01TESTLESSON0000000002",
  url: "/courses/course%3A01TESTCOURSE00000000001/lessons/lesson%3A01TESTLESSON0000000002",
};

/**
 * Lesson 3 has `transcription: { version: 1, ..., cueCount: 0, cues: [] }`.
 * This passes schema validation but triggers the `no_cues` ineligibility reason.
 */
const NO_CUES_LESSON = {
  courseId: "course:01TESTCOURSE00000000001",
  lessonId: "lesson:01TESTLESSON0000000003",
  url: "/courses/course%3A01TESTCOURSE00000000001/lessons/lesson%3A01TESTLESSON0000000003",
};

/**
 * Lesson 4 has an auto-generated (`isAutoGenerated: true`) v1 transcript.
 * Used to verify the "Auto" source badge in TranscriptPanel.
 */
const AUTO_TRANSCRIPT_LESSON = {
  courseId: "course:01TESTCOURSE00000000001",
  lessonId: "lesson:01TESTLESSON0000000004",
  url: "/courses/course%3A01TESTCOURSE00000000001/lessons/lesson%3A01TESTLESSON0000000004",
};

describe("Lesson Transcript — Timestamp Mode", () => {
  beforeEach(() => {
    cy.loginAsAdmin();
  });

  it("shows the Transcription tab in fullscreen mode", () => {
    cy.visit(TRANSCRIPT_LESSON.url);

    // Wait for the lesson page to fully load
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    // Switch to fullscreen layout to reveal the transcript tab
    cy.contains("button", "Fullscreen").click();

    cy.contains("Transcription").should("be.visible");
  });

  it("displays transcript cues in timestamp mode", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();

    // Click the Transcription tab
    cy.contains("Transcription").click();

    // Wait for the transcript panel to render
    cy.get('[data-testid="transcript-panel"]', { timeout: 10000 }).should(
      "be.visible",
    );

    // Cue list should be visible by default (timestamp mode)
    cy.get('[data-testid="transcript-cue-list"]').should("be.visible");

    // At least one cue item should be rendered
    cy.get('[data-testid="transcript-cue"]').should(
      "have.length.greaterThan",
      0,
    );
  });

  it("shows cue timestamps and text content", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[data-testid="transcript-panel"]', { timeout: 10000 }).should(
      "be.visible",
    );

    // First cue starts at 0ms → timestamp "0:00"
    cy.get('[data-testid="transcript-cue"]')
      .first()
      .within(() => {
        cy.get('[aria-label^="Time:"]').should("contain", "0:00");
      });

    // Fixture transcript text from scripts/fixtures/lessons.ts
    cy.contains("Welcome to the Fastify course.", { timeout: 5000 }).should(
      "be.visible",
    );
  });

  it("shows the Manual source badge", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[data-testid="transcript-panel"]', { timeout: 10000 }).should(
      "be.visible",
    );

    cy.contains("Manual").should("be.visible");
  });

  it("shows hours format (H:MM:SS) for cues with a start time over one hour", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[data-testid="transcript-panel"]', { timeout: 10000 }).should(
      "be.visible",
    );

    // Cue c4 starts at 3 600 000 ms = exactly 1:00:00.
    cy.get('[data-testid="transcript-cue"]')
      .last()
      .within(() => {
        cy.get('[aria-label^="Time:"]').should("contain", "1:00:00");
      });
  });
});

describe("Lesson Transcript — Paragraph Mode", () => {
  beforeEach(() => {
    cy.loginAsAdmin();
  });

  it("switches to paragraph mode and shows paragraph content", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[data-testid="transcript-panel"]', { timeout: 10000 }).should(
      "be.visible",
    );

    // Switch to paragraph mode
    cy.get('[data-testid="transcript-mode-paragraph"]').click();

    // Paragraph list should appear and cue list should disappear
    cy.get('[data-testid="transcript-paragraph-list"]').should("be.visible");
    cy.get('[data-testid="transcript-cue-list"]').should("not.exist");

    // Transcript text should still be visible
    cy.contains("Welcome to the Fastify course.").should("be.visible");
  });

  it("can switch back to timestamp mode from paragraph mode", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[data-testid="transcript-panel"]', { timeout: 10000 }).should(
      "be.visible",
    );

    cy.get('[data-testid="transcript-mode-paragraph"]').click();
    cy.get('[data-testid="transcript-paragraph-list"]').should("be.visible");

    cy.get('[data-testid="transcript-mode-timestamp"]').click();
    cy.get('[data-testid="transcript-cue-list"]').should("be.visible");
    cy.get('[data-testid="transcript-paragraph-list"]').should("not.exist");
  });

  it("shows multiple paragraphs when transcript has speaker changes", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[data-testid="transcript-panel"]', { timeout: 10000 }).should(
      "be.visible",
    );

    cy.get('[data-testid="transcript-mode-paragraph"]').click();

    // Speaker change (Alice→Bob at c2) and large gap (c3→c4) create exactly 3 paragraphs.
    cy.get('[data-testid="transcript-paragraph"]').should("have.length", 3);
  });
});

describe("Lesson Transcript — Empty State", () => {
  beforeEach(() => {
    cy.loginAsAdmin();
  });

  it("shows no-transcript message for a lesson without a Phase 1 transcript", () => {
    cy.visit(NO_TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    // Should show empty state, not a transcript panel
    cy.get('[data-testid="transcript-empty"]', { timeout: 10000 }).should(
      "be.visible",
    );

    cy.get('[data-testid="transcript-panel"]').should("not.exist");
  });

  it("shows empty-cues message for a lesson whose transcript has zero cues", () => {
    cy.visit(NO_CUES_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    // Valid v1 schema with empty cues → "no_cues" reason → distinct message
    cy.get('[data-testid="transcript-empty"]', { timeout: 10000 }).should(
      "be.visible",
    );

    cy.contains("The transcript for this lesson is empty.").should(
      "be.visible",
    );

    cy.get('[data-testid="transcript-panel"]').should("not.exist");
  });
});

describe("Lesson Transcript — Source Badge", () => {
  beforeEach(() => {
    cy.loginAsAdmin();
  });

  it("shows the Auto source badge for auto-generated transcripts", () => {
    cy.visit(AUTO_TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[data-testid="transcript-panel"]', { timeout: 10000 }).should(
      "be.visible",
    );

    cy.contains("Auto").should("be.visible");
  });
});

describe("Lesson Transcript — Access Control", () => {
  it("requires authentication to view the lesson transcript", () => {
    cy.clearAllCookies();
    cy.clearAllLocalStorage();

    cy.visit(TRANSCRIPT_LESSON.url);

    // Unauthenticated users should be redirected to sign-in
    cy.url().should("include", "/signin");
  });
});
