/**
 * Lesson Transcript E2E Tests — Phases 1, 3 & 5
 *
 * Verifies that:
 *   - The lesson page shows a Transcription tab in fullscreen mode.
 *   - A lesson with a valid Phase 1 transcript displays cues in timestamp mode.
 *   - Switching to paragraph mode renders paragraph content (including multiple
 *     paragraphs when speaker changes / large gaps are present).
 *   - A lesson with no valid transcript shows an empty-state message.
 *   - A lesson with an empty cues array shows the "empty" state message.
 *   - An auto-generated transcript shows the "Auto" source badge.
 *   - Cues with a start time > 1 hour render in H:MM:SS format.
 *   - Search finds matches in both timestamp and paragraph modes (Phase 5).
 *   - Search query is preserved when switching between modes (Phase 5).
 *
 * Uses deterministic fixture IDs seeded by the CI pipeline.
 */

/** Milliseconds to wait for the lesson page to fully load. */
const LESSON_LOAD_TIMEOUT = 15000;

/** Fixture IDs for the "What is Fastify?" preview lesson (Phase 1 transcript).
 *  Transcript has 5 cues: c0–c1 (Alice), c2–c3 (Bob), c4 at 1 h (Alice).
 *  Speaker change between c1→c2 + large gap before c4 produce 3 paragraphs. */
const TRANSCRIPT_LESSON = {
  courseId: "course:01TESTCOURSE00000000001",
  lessonId: "lesson:01TESTLESSON0000000001",
  url: "/courses/course%3A01TESTCOURSE00000000001/lessons/lesson%3A01TESTLESSON0000000001",
};

/**
 * Lesson 2 has `transcription: { segments: [] }` (old-format, empty segments).
 * This triggers the `invalid_schema` reason and renders the empty-state UI.
 */
const NO_TRANSCRIPT_LESSON = {
  courseId: "course:01TESTCOURSE00000000001",
  lessonId: "lesson:01TESTLESSON0000000002",
  url: "/courses/course%3A01TESTCOURSE00000000001/lessons/lesson%3A01TESTLESSON0000000002",
};

/**
 * Lesson 3 has `transcription: { version: 1, ..., cueCount: 0, cues: [] }`.
 * This passes schema validation but triggers the `no_cues` ineligibility reason.
 */
const NO_CUES_LESSON = {
  courseId: "course:01TESTCOURSE00000000001",
  lessonId: "lesson:01TESTLESSON0000000003",
  url: "/courses/course%3A01TESTCOURSE00000000001/lessons/lesson%3A01TESTLESSON0000000003",
};

/**
 * Lesson 4 has an auto-generated (`isAutoGenerated: true`) v1 transcript.
 * Used to verify the "Auto" source badge in TranscriptPanel.
 */
const AUTO_TRANSCRIPT_LESSON = {
  courseId: "course:01TESTCOURSE00000000001",
  lessonId: "lesson:01TESTLESSON0000000004",
  url: "/courses/course%3A01TESTCOURSE00000000001/lessons/lesson%3A01TESTLESSON0000000004",
};

describe("Lesson Transcript — Timestamp Mode", () => {
  beforeEach(() => {
    cy.loginAsAdmin();
  });

  it("shows the Transcription tab in fullscreen mode", () => {
    cy.visit(TRANSCRIPT_LESSON.url);

    // Wait for the lesson page to fully load
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    // Switch to fullscreen layout to reveal the transcript tab
    cy.contains("button", "Fullscreen").click();

    cy.contains("Transcription").should("be.visible");
  });

  it("displays transcript cues in timestamp mode", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();

    // Click the Transcription tab
    cy.contains("Transcription").click();

    // Wait for the transcript panel to render
    cy.get('[aria-label="Lesson transcript"]', { timeout: 10000 }).should(
      "be.visible",
    );

    // Cue list should be visible by default (timestamp mode)
    cy.get('[aria-label="Transcript cues"]').should("be.visible");

    // At least one cue item should be rendered
    cy.get('[aria-label="Transcript cues"] li').should(
      "have.length.greaterThan",
      0,
    );
  });

  it("shows cue timestamps and text content", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[aria-label="Lesson transcript"]', { timeout: 10000 }).should(
      "be.visible",
    );

    // First cue starts at 0ms → timestamp "0:00"
    cy.get('[aria-label="Transcript cues"] li')
      .first()
      .within(() => {
        cy.get('[aria-label^="Time:"]').should("contain", "0:00");
      });

    // Fixture transcript text from scripts/fixtures/lessons.ts
    cy.contains("Welcome to the Fastify course.", { timeout: 5000 }).should(
      "be.visible",
    );
  });

  it("shows the Manual source badge", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[aria-label="Lesson transcript"]', { timeout: 10000 }).should(
      "be.visible",
    );

    cy.contains("Manual").should("be.visible");
  });

  it("shows hours format (H:MM:SS) for cues with a start time over one hour", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[aria-label="Lesson transcript"]', { timeout: 10000 }).should(
      "be.visible",
    );

    // Cue c4 starts at 3 600 000 ms = exactly 1:00:00.
    cy.get('[aria-label="Transcript cues"] li')
      .last()
      .within(() => {
        cy.get('[aria-label^="Time:"]').should("contain", "1:00:00");
      });
  });
});

describe("Lesson Transcript — Paragraph Mode", () => {
  beforeEach(() => {
    cy.loginAsAdmin();
  });

  it("switches to paragraph mode and shows paragraph content", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[aria-label="Lesson transcript"]', { timeout: 10000 }).should(
      "be.visible",
    );

    // Switch to paragraph mode
    cy.contains('[aria-label="Lesson transcript"] button', "Paragraph").click();

    // Paragraph list should appear and cue list should disappear
    cy.get('[aria-label="Transcript paragraphs"]').should("be.visible");
    cy.get('[aria-label="Transcript cues"]').should("not.exist");

    // Transcript text should still be visible
    cy.contains("Welcome to the Fastify course.").should("be.visible");
  });

  it("can switch back to timestamp mode from paragraph mode", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[aria-label="Lesson transcript"]', { timeout: 10000 }).should(
      "be.visible",
    );

    cy.contains('[aria-label="Lesson transcript"] button', "Paragraph").click();
    cy.get('[aria-label="Transcript paragraphs"]').should("be.visible");

    cy.contains(
      '[aria-label="Lesson transcript"] button',
      "Timestamps",
    ).click();
    cy.get('[aria-label="Transcript cues"]').should("be.visible");
    cy.get('[aria-label="Transcript paragraphs"]').should("not.exist");
  });

  it("shows multiple paragraphs when transcript has speaker changes", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[aria-label="Lesson transcript"]', { timeout: 10000 }).should(
      "be.visible",
    );

    cy.contains('[aria-label="Lesson transcript"] button', "Paragraph").click();

    // Speaker change (Alice→Bob at c2) and large gap (c3→c4) create exactly 3 paragraphs.
    cy.get('[aria-label="Transcript paragraphs"] li').should("have.length", 3);
  });
});

describe("Lesson Transcript — Empty State", () => {
  beforeEach(() => {
    cy.loginAsAdmin();
  });

  it("shows no-transcript message for a lesson without a Phase 1 transcript", () => {
    cy.visit(NO_TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    // Should show empty state, not a transcript panel
    cy.get('[role="status"]', { timeout: 10000 }).should("be.visible");

    cy.get('[aria-label="Lesson transcript"]').should("not.exist");
  });

  it("shows empty-cues message for a lesson whose transcript has zero cues", () => {
    cy.visit(NO_CUES_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    // Valid v1 schema with empty cues → "no_cues" reason → distinct message
    cy.get('[role="status"]', { timeout: 10000 }).should("be.visible");

    cy.contains("The transcript for this lesson is empty.").should(
      "be.visible",
    );

    cy.get('[aria-label="Lesson transcript"]').should("not.exist");
  });
});

describe("Lesson Transcript — Source Badge", () => {
  beforeEach(() => {
    cy.loginAsAdmin();
  });

  it("shows the Auto source badge for auto-generated transcripts", () => {
    cy.visit(AUTO_TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[aria-label="Lesson transcript"]', { timeout: 10000 }).should(
      "be.visible",
    );

    cy.contains("Auto").should("be.visible");
  });
});

describe("Lesson Transcript — Search (Phase 3)", () => {
  beforeEach(() => {
    cy.loginAsAdmin();
  });

  it("opens the search bar and finds matches for a query", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[aria-label="Lesson transcript"]', { timeout: 10000 }).should(
      "be.visible",
    );

    // Open search bar
    cy.get('[aria-label="Toggle transcript search"]').click();

    // Search bar should appear
    cy.get('[role="search"][aria-label="Transcript search"]').should(
      "be.visible",
    );

    // Type a search query that matches at least 2 cues ("Fastify" appears in c0 and c1)
    cy.get('[aria-label="Transcript search query"]').type("Fastify");

    // Match counter should show results
    cy.get("#transcript-search-status").should("contain", "1 / 2");

    // Navigate to next match
    cy.get('[aria-label="Next match"]').click();
    cy.get("#transcript-search-status").should("contain", "2 / 2");

    // Navigate to previous match
    cy.get('[aria-label="Previous match"]').click();
    cy.get("#transcript-search-status").should("contain", "1 / 2");
  });

  it("shows 0 results for a query with no matches", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[aria-label="Lesson transcript"]', { timeout: 10000 }).should(
      "be.visible",
    );

    cy.get('[aria-label="Toggle transcript search"]').click();
    cy.get('[aria-label="Transcript search query"]').type(
      "zzzznonexistentterm",
    );

    cy.get("#transcript-search-status").should("contain", "0 results");

    // Navigation buttons should be disabled
    cy.get('[aria-label="Next match"]').should("be.disabled");
    cy.get('[aria-label="Previous match"]').should("be.disabled");
  });

  it("closes the search bar and clears the query", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[aria-label="Lesson transcript"]', { timeout: 10000 }).should(
      "be.visible",
    );

    // Open and type
    cy.get('[aria-label="Toggle transcript search"]').click();
    cy.get('[aria-label="Transcript search query"]').type("Fastify");
    cy.get("#transcript-search-status").should("contain", "1 / 2");

    // Close search
    cy.get('[aria-label="Close search"]').click();

    // Search bar should disappear
    cy.get('[role="search"][aria-label="Transcript search"]').should(
      "not.exist",
    );
  });
});

describe("Lesson Transcript — Follow Playback (Phase 3)", () => {
  beforeEach(() => {
    cy.loginAsAdmin();
  });

  it("shows the Follow button in timestamp mode and toggles it", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[aria-label="Lesson transcript"]', { timeout: 10000 }).should(
      "be.visible",
    );

    // Follow button should be visible and pressed by default
    cy.contains('[aria-label="Transcript controls"] button', "Follow")
      .should("be.visible")
      .and("have.attr", "aria-pressed", "true");

    // Toggle Follow off
    cy.contains('[aria-label="Transcript controls"] button', "Follow").click();
    cy.contains('[aria-label="Transcript controls"] button', "Follow").should(
      "have.attr",
      "aria-pressed",
      "false",
    );

    // Toggle Follow back on
    cy.contains('[aria-label="Transcript controls"] button', "Follow").click();
    cy.contains('[aria-label="Transcript controls"] button', "Follow").should(
      "have.attr",
      "aria-pressed",
      "true",
    );
  });

  it("hides the Follow button in paragraph mode", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[aria-label="Lesson transcript"]', { timeout: 10000 }).should(
      "be.visible",
    );

    // Switch to paragraph mode
    cy.contains('[aria-label="Lesson transcript"] button', "Paragraph").click();

    // Follow button should not be visible in paragraph mode
    cy.contains('[aria-label="Transcript controls"] button', "Follow").should(
      "not.exist",
    );
  });
});

describe("Lesson Transcript — Cue Interaction (Phase 3)", () => {
  beforeEach(() => {
    cy.loginAsAdmin();
  });

  it("cues are interactive buttons when video is present", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[aria-label="Lesson transcript"]', { timeout: 10000 }).should(
      "be.visible",
    );

    // Cues should have role="button" since the lesson has a video URL
    cy.get('[aria-label="Transcript cues"] li')
      .first()
      .should("have.attr", "role", "button")
      .and("have.attr", "tabindex", "0");
  });

  it("paragraphs are interactive buttons when video is present", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[aria-label="Lesson transcript"]', { timeout: 10000 }).should(
      "be.visible",
    );

    // Switch to paragraph mode
    cy.contains('[aria-label="Lesson transcript"] button', "Paragraph").click();

    // Paragraphs should have role="button" since the lesson has a video URL
    cy.get('[aria-label="Transcript paragraphs"] li')
      .first()
      .should("have.attr", "role", "button")
      .and("have.attr", "tabindex", "0");
  });
});

describe("Lesson Transcript — Access Control", () => {
  it("requires authentication to view the lesson transcript", () => {
    cy.clearAllCookies();
    cy.clearAllLocalStorage();

    cy.visit(TRANSCRIPT_LESSON.url);

    // Unauthenticated users should be redirected to sign-in
    cy.url().should("include", "/signin");
  });
});

describe("Lesson Transcript — Search in Paragraph Mode (Phase 5)", () => {
  beforeEach(() => {
    cy.loginAsAdmin();
  });

  it("search finds the same matches in paragraph mode as in timestamp mode", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[aria-label="Lesson transcript"]', { timeout: 10000 }).should(
      "be.visible",
    );

    // Switch to paragraph mode first
    cy.contains('[aria-label="Lesson transcript"] button', "Paragraph").click();
    cy.get('[aria-label="Transcript paragraphs"]').should("be.visible");

    // Open search bar
    cy.get('[aria-label="Toggle transcript search"]').click();
    cy.get('[role="search"][aria-label="Transcript search"]').should(
      "be.visible",
    );

    // "Fastify" appears in two cues (c0 and c1) — same as in timestamp mode
    cy.get('[aria-label="Transcript search query"]').type("Fastify");
    cy.get("#transcript-search-status").should("contain", "1 / 2");

    // Navigate to next match
    cy.get('[aria-label="Next match"]').click();
    cy.get("#transcript-search-status").should("contain", "2 / 2");

    // Navigate back to first match
    cy.get('[aria-label="Previous match"]').click();
    cy.get("#transcript-search-status").should("contain", "1 / 2");
  });

  it("search query and match position are preserved when switching between modes", () => {
    cy.visit(TRANSCRIPT_LESSON.url);
    cy.contains("Back to Course", { timeout: LESSON_LOAD_TIMEOUT }).should(
      "be.visible",
    );

    cy.contains("button", "Fullscreen").click();
    cy.contains("Transcription").click();

    cy.get('[aria-label="Lesson transcript"]', { timeout: 10000 }).should(
      "be.visible",
    );

    // Open search and type a query in timestamp mode
    cy.get('[aria-label="Toggle transcript search"]').click();
    cy.get('[aria-label="Transcript search query"]').type("Fastify");
    cy.get("#transcript-search-status").should("contain", "1 / 2");

    // Advance to the second match
    cy.get('[aria-label="Next match"]').click();
    cy.get("#transcript-search-status").should("contain", "2 / 2");

    // Switch to paragraph mode — query and match index should persist
    cy.contains('[aria-label="Lesson transcript"] button', "Paragraph").click();
    cy.get('[aria-label="Transcript paragraphs"]').should("be.visible");
    cy.get("#transcript-search-status").should("contain", "2 / 2");

    // Switch back to timestamp mode — query and match index should still persist
    cy.contains(
      '[aria-label="Lesson transcript"] button',
      "Timestamps",
    ).click();
    cy.get('[aria-label="Transcript cues"]').should("be.visible");
    cy.get("#transcript-search-status").should("contain", "2 / 2");
  });
});
