/**
 * Server-side transcript validation utilities.
 *
 * This module provides the Zod schema and publish-eligibility helpers that
 * mirror the frontend `~/lib/transcript` utilities without pulling in any
 * browser-only APIs (DOMParser, etc.).
 */
import * as z from "zod";

// ---------------------------------------------------------------------------
// Schemas
// ---------------------------------------------------------------------------

export const transcriptCueSchema = z
  .object({
    id: z.string(),
    startMs: z.number().int().min(0),
    endMs: z.number().int().min(0),
    text: z.string(),
    speaker: z.string().optional(),
  })
  .refine((cue) => cue.endMs >= cue.startMs, {
    message: "Cue endMs must be greater than or equal to startMs",
    path: ["endMs"],
  });

export const transcriptDataSchema = z
  .object({
    version: z.literal(1),
    language: z.string().min(1),
    source: z.enum(["manual", "auto"]),
    sourceProvider: z.string().optional(),
    sourceTrackId: z.string().optional(),
    lastFetchedAt: z.string().datetime({ offset: true }).optional(),
    isAutoGenerated: z.boolean(),
    cueCount: z.number().int().min(0),
    durationMs: z.number().int().min(0),
    cues: z.array(transcriptCueSchema),
  })
  .superRefine((data, ctx) => {
    if (data.cueCount !== data.cues.length) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "cueCount must match cues.length",
        path: ["cueCount"],
      });
    }

    const lastCue = data.cues.at(-1);
    if (lastCue && data.durationMs < lastCue.endMs) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message:
          "durationMs must be greater than or equal to the last cue endMs",
        path: ["durationMs"],
      });
    }
  });

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Validate a raw JSON value as a transcript data payload.
 * Returns `true` when valid, `false` otherwise.
 */
export function isValidTranscriptData(raw: unknown): boolean {
  return transcriptDataSchema.safeParse(raw).success;
}

// ---------------------------------------------------------------------------
// Publish eligibility
// ---------------------------------------------------------------------------

/**
 * Reasons why a transcript is not publish-eligible.
 */
export type TranscriptIneligibleReason =
  | "missing"
  | "invalid_schema"
  | "no_cues";

/**
 * Result of checking transcript publish eligibility.
 */
export type TranscriptEligibility =
  | { eligible: true }
  | { eligible: false; reason: TranscriptIneligibleReason };

/**
 * Determine whether a lesson transcript is ready for publishing.
 *
 * Rules (from blueprint):
 *   - Non-video lessons are always eligible (pass `hasVideo = false`).
 *   - Video lessons with a valid transcript containing ≥1 cue are eligible.
 *   - Empty or missing transcripts block publish.
 */
export function checkTranscriptEligibility(
  transcription: unknown,
  hasVideo: boolean,
): TranscriptEligibility {
  if (!hasVideo) return { eligible: true };

  if (transcription === null || transcription === undefined) {
    return { eligible: false, reason: "missing" };
  }

  const result = transcriptDataSchema.safeParse(transcription);
  if (!result.success) {
    return { eligible: false, reason: "invalid_schema" };
  }

  if (result.data.cues.length === 0) {
    return { eligible: false, reason: "no_cues" };
  }

  return { eligible: true };
}
