import {
  checkTranscriptEligibility,
  isValidTranscriptData,
} from "../transcript.js";
import { describe, expect, test } from "vitest";

/** Helper to build a valid transcript payload. */
function makeTranscript(overrides: Record<string, unknown> = {}) {
  return {
    version: 1,
    language: "en",
    source: "manual",
    isAutoGenerated: false,
    cueCount: 1,
    durationMs: 5000,
    cues: [{ id: "c1", startMs: 0, endMs: 5000, text: "Hello world" }],
    ...overrides,
  };
}

describe("checkTranscriptEligibility", () => {
  test("non-video lesson is always eligible", () => {
    const result = checkTranscriptEligibility(null, false);
    expect(result).toEqual({ eligible: true });
  });

  test("non-video lesson with undefined transcript is eligible", () => {
    const result = checkTranscriptEligibility(undefined, false);
    expect(result).toEqual({ eligible: true });
  });

  test("video lesson with null transcript returns missing", () => {
    const result = checkTranscriptEligibility(null, true);
    expect(result).toEqual({ eligible: false, reason: "missing" });
  });

  test("video lesson with undefined transcript returns missing", () => {
    const result = checkTranscriptEligibility(undefined, true);
    expect(result).toEqual({ eligible: false, reason: "missing" });
  });

  test("video lesson with malformed transcript returns invalid_schema", () => {
    const result = checkTranscriptEligibility({ bad: "data" }, true);
    expect(result).toEqual({ eligible: false, reason: "invalid_schema" });
  });

  test("video lesson with non-object transcript returns invalid_schema", () => {
    const result = checkTranscriptEligibility("not-json", true);
    expect(result).toEqual({ eligible: false, reason: "invalid_schema" });
  });

  test("video lesson with empty cues returns no_cues", () => {
    const transcript = makeTranscript({ cueCount: 0, cues: [] });
    const result = checkTranscriptEligibility(transcript, true);
    expect(result).toEqual({ eligible: false, reason: "no_cues" });
  });

  test("video lesson with valid transcript and cues is eligible", () => {
    const transcript = makeTranscript();
    const result = checkTranscriptEligibility(transcript, true);
    expect(result).toEqual({ eligible: true });
  });

  test("video lesson with mismatched cueCount returns invalid_schema", () => {
    const transcript = makeTranscript({ cueCount: 99 });
    const result = checkTranscriptEligibility(transcript, true);
    expect(result).toEqual({ eligible: false, reason: "invalid_schema" });
  });
});

describe("isValidTranscriptData", () => {
  test("returns true for valid transcript", () => {
    expect(isValidTranscriptData(makeTranscript())).toBe(true);
  });

  test("returns false for null", () => {
    expect(isValidTranscriptData(null)).toBe(false);
  });

  test("returns false for invalid object", () => {
    expect(isValidTranscriptData({ version: 2 })).toBe(false);
  });
});
