/**
 * Transcript domain utilities for Phase 1.
 *
 * Covers:
 *   - TypeScript types for the normalized transcript payload.
 *   - VTT → cue parser.
 *   - Cue → paragraph chunker (speaker change, 2.5 s gap, 600-char limit).
 *   - Simple in-memory cue search.
 *   - Zod validator for persisted transcript JSON.
 *   - Publish-eligibility helper.
 */
import * as z from "zod";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * A single timed caption entry derived from a VTT file.
 */
export interface TranscriptCue {
  /** Stable identifier (positional index as string, or VTT cue id). */
  id: string;
  /** Start of the cue in milliseconds. */
  startMs: number;
  /** End of the cue in milliseconds. */
  endMs: number;
  /** Visible caption text (HTML stripped). */
  text: string;
  /** Optional speaker label (from VTT `<v>` voice tag or NOTE metadata). */
  speaker?: string;
}

/**
 * Source of a transcript (how it was obtained).
 */
export type TranscriptSource = "manual" | "auto";

/**
 * Full normalized transcript payload stored in `course_lesson.transcription`.
 */
export interface TranscriptData {
  /** Schema version. Increment when the shape changes incompatibly. */
  version: 1;
  /** BCP-47 language tag, e.g. "en". */
  language: string;
  /**
   * How the transcript was obtained:
   * - `"manual"` = admin uploaded or selected a manual caption track.
   * - `"auto"`   = fetched from an auto-generated provider track.
   */
  source: TranscriptSource;
  /** Provider that originally hosted the transcript (e.g. "youtube"). */
  sourceProvider?: string;
  /** Provider-specific track identifier (e.g. YouTube caption track ID). */
  sourceTrackId?: string;
  /** ISO 8601 timestamp of the last fetch/upload. */
  lastFetchedAt?: string;
  /** True when the underlying track was auto-generated (not manually authored). */
  isAutoGenerated: boolean;
  /** Number of cues in the cue array. */
  cueCount: number;
  /** Total duration covered by the last cue in milliseconds. */
  durationMs: number;
  /** Ordered list of caption cues. */
  cues: TranscriptCue[];
}

/**
 * A group of consecutive cues merged into a readable paragraph.
 */
export interface TranscriptParagraph {
  /** Index of the first cue in this paragraph. */
  firstCueIndex: number;
  /** Index of the last cue in this paragraph (inclusive). */
  lastCueIndex: number;
  /** Start time of the first cue in milliseconds. */
  startMs: number;
  /** End time of the last cue in milliseconds. */
  endMs: number;
  /** Combined text content. */
  text: string;
  /** Speaker label if all cues in this paragraph share the same speaker. */
  speaker?: string;
}

/**
 * A single match from a transcript search.
 */
export interface TranscriptSearchMatch {
  /** Index of the cue in the source `TranscriptData.cues` array. */
  cueIndex: number;
  /** The matching cue. */
  cue: TranscriptCue;
  /** Index of the match within `cue.text` (for highlight ranges). */
  matchIndex: number;
}

/**
 * Result returned by `searchTranscript`. */
export interface TranscriptSearchResult {
  query: string;
  matches: TranscriptSearchMatch[];
}

// ---------------------------------------------------------------------------
// VTT parser
// ---------------------------------------------------------------------------

/** Maximum milliseconds represented in a VTT timestamp (99:59:59.999). */
const MAX_VTT_MS = 359_999_999;

/**
 * Parse a VTT timestamp string ("HH:MM:SS.mmm" or "MM:SS.mmm") to milliseconds.
 *
 * Returns `null` for malformed values so the caller can skip or surface errors.
 */
export function parseVttTimestamp(raw: string): number | null {
  const trimmed = raw.trim();
  // Accept HH:MM:SS.mmm, H:MM:SS.mmm, MM:SS.mmm, M:SS.mmm
  const match = trimmed.match(
    /^(\d{1,2}):(\d{2}):(\d{2})\.(\d{1,3})$|^(\d{1,2}):(\d{2})\.(\d{1,3})$/,
  );
  if (!match) return null;

  let hours = 0;
  let minutes: number;
  let seconds: number;
  let millis: number;

  if (match[1] !== undefined) {
    // HH:MM:SS.mmm
    hours = parseInt(match[1], 10);
    minutes = parseInt(match[2], 10);
    seconds = parseInt(match[3], 10);
    millis = parseInt(match[4].padEnd(3, "0"), 10);
  } else {
    // MM:SS.mmm
    minutes = parseInt(match[5], 10);
    seconds = parseInt(match[6], 10);
    millis = parseInt(match[7].padEnd(3, "0"), 10);
  }

  if (minutes > 59 || seconds > 59) return null;

  const result =
    hours * 3_600_000 + minutes * 60_000 + seconds * 1_000 + millis;
  if (result > MAX_VTT_MS) return null;
  return result;
}

/** Strip HTML tags from VTT cue text (including `<c>`, `<v Name>`, etc.). */
function stripVttTags(text: string): string {
  // Use DOMParser for safe, complete entity decoding and tag stripping.
  // DOMParser correctly handles all HTML entity types (named, numeric, hex)
  // and malformed/unclosed tags, without the incomplete-sanitization risks of
  // regex-based stripping.
  //
  // Browser-only: this function is called only from parseVtt which runs
  // exclusively in the browser (apps/web client-side bundle).
  const doc = new DOMParser().parseFromString(text, "text/html");
  return (doc.body.textContent ?? "").trim();
}

/**
 * Extract the speaker from a `<v Speaker Name>` voice tag if present.
 * Returns `undefined` when no voice tag is found.
 */
function extractSpeaker(rawText: string): string | undefined {
  const match = rawText.match(/<v\s+([^>]+)>/);
  return match ? match[1].trim() : undefined;
}

/**
 * A parse warning emitted when a cue has non-fatal issues.
 */
export interface VttParseWarning {
  /** 1-based line number in the VTT source. */
  line: number;
  message: string;
}

/**
 * Result of `parseVtt`.
 */
export interface VttParseResult {
  cues: TranscriptCue[];
  warnings: VttParseWarning[];
}

/**
 * Parse a WebVTT string into a normalized list of `TranscriptCue` objects.
 *
 * - Strips HTML tags (keeps plain text).
 * - Extracts `<v Name>` speaker tags.
 * - Skips NOTE blocks and STYLE blocks.
 * - Collects per-cue warnings for malformed timestamps without aborting.
 */
export function parseVtt(vttText: string): VttParseResult {
  const cues: TranscriptCue[] = [];
  const warnings: VttParseWarning[] = [];

  const rawLines = vttText
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n")
    .split("\n");

  // Validate WEBVTT header
  if (!rawLines[0]?.trim().startsWith("WEBVTT")) {
    warnings.push({ line: 1, message: "Missing WEBVTT header" });
  }

  let i = 1; // skip header line
  let cueIndex = 0;

  while (i < rawLines.length) {
    const line = rawLines[i];

    // Skip blank lines
    if (line.trim() === "") {
      i++;
      continue;
    }

    // Skip NOTE blocks
    if (line.trim().startsWith("NOTE")) {
      while (i < rawLines.length && rawLines[i].trim() !== "") {
        i++;
      }
      continue;
    }

    // Skip STYLE blocks
    if (line.trim().startsWith("STYLE")) {
      while (i < rawLines.length && rawLines[i].trim() !== "") {
        i++;
      }
      continue;
    }

    // Skip REGION blocks
    if (line.trim().startsWith("REGION")) {
      while (i < rawLines.length && rawLines[i].trim() !== "") {
        i++;
      }
      continue;
    }

    // Detect a timing line (contains " --> ")
    const isTimingLine = line.includes(" --> ");

    let cueId: string | undefined;
    let timingLine: string;
    const textLines: string[] = [];

    if (isTimingLine) {
      timingLine = line;
    } else {
      // Could be a cue ID
      cueId = line.trim();
      i++;
      if (i >= rawLines.length) break;
      timingLine = rawLines[i];
      if (!timingLine.includes(" --> ")) {
        // Not a valid cue block — skip
        warnings.push({
          line: i + 1,
          message: `Expected timing line after cue id "${cueId}", got: "${timingLine}"`,
        });
        i++;
        continue;
      }
    }

    const timingLineNum = i + 1;
    i++;

    // Collect payload lines (until blank line or EOF)
    while (i < rawLines.length && rawLines[i].trim() !== "") {
      textLines.push(rawLines[i]);
      i++;
    }

    // Parse timing
    // VTT timing: "00:00:01.000 --> 00:00:03.500 position:50%"
    const timingParts = timingLine.split(" --> ");
    const startRaw = timingParts[0].trim();
    // strip any cue settings (position, align, etc.) from end time
    const endRaw = (timingParts[1] ?? "").split(/\s+/)[0].trim();

    const startMs = parseVttTimestamp(startRaw);
    const endMs = parseVttTimestamp(endRaw);

    if (startMs === null) {
      warnings.push({
        line: timingLineNum,
        message: `Malformed start timestamp: "${startRaw}"`,
      });
      continue;
    }
    if (endMs === null) {
      warnings.push({
        line: timingLineNum,
        message: `Malformed end timestamp: "${endRaw}"`,
      });
      continue;
    }
    if (endMs < startMs) {
      warnings.push({
        line: timingLineNum,
        message: `End time (${endMs}ms) is before start time (${startMs}ms)`,
      });
      // Still include the cue — clamp end to start
    }

    const rawText = textLines.join("\n");
    if (!rawText.trim()) {
      // Empty cue — skip silently
      continue;
    }

    const speaker = extractSpeaker(rawText);
    const text = stripVttTags(rawText);

    cues.push({
      id: cueId ?? String(cueIndex),
      startMs,
      endMs: endMs < startMs ? startMs : endMs,
      text,
      ...(speaker ? { speaker } : {}),
    });
    cueIndex++;
  }

  return { cues, warnings };
}

/**
 * Build a `TranscriptData` payload from a parsed VTT result.
 */
export function buildTranscriptData(
  result: VttParseResult,
  options: {
    language?: string;
    source?: TranscriptSource;
    sourceProvider?: string;
    sourceTrackId?: string;
    isAutoGenerated?: boolean;
  } = {},
): TranscriptData {
  const { cues } = result;
  const lastCue = cues[cues.length - 1];
  return {
    version: 1,
    language: options.language ?? "en",
    source: options.source ?? "manual",
    ...(options.sourceProvider
      ? { sourceProvider: options.sourceProvider }
      : {}),
    ...(options.sourceTrackId ? { sourceTrackId: options.sourceTrackId } : {}),
    lastFetchedAt: new Date().toISOString(),
    isAutoGenerated: options.isAutoGenerated ?? false,
    cueCount: cues.length,
    durationMs: lastCue?.endMs ?? 0,
    cues,
  };
}

// ---------------------------------------------------------------------------
// Paragraph chunker
// ---------------------------------------------------------------------------

/**
 * Gap in milliseconds between two cues that triggers a new paragraph.
 * Blueprint spec: 2.5 seconds.
 */
const PARAGRAPH_GAP_THRESHOLD_MS = 2_500;

/**
 * Target paragraph length in characters. New paragraph starts when exceeded.
 * Blueprint spec: 500-700 chars — we use 600 as the soft limit.
 */
const PARAGRAPH_CHAR_LIMIT = 600;

/**
 * Derive readable paragraphs from an ordered cue array.
 *
 * A new paragraph starts when:
 *   1. The speaker changes between consecutive cues.
 *   2. The gap between `endMs` of the previous cue and `startMs` of the next is ≥ 2.5 s.
 *   3. The accumulated text length of the current paragraph exceeds 600 characters.
 */
export function buildParagraphs(cues: TranscriptCue[]): TranscriptParagraph[] {
  if (cues.length === 0) return [];

  const paragraphs: TranscriptParagraph[] = [];
  let groupStart = 0;
  let accText = cues[0].text;
  let groupSpeaker: string | undefined = cues[0].speaker;

  const flush = (endIdx: number) => {
    const firstCue = cues[groupStart];
    const lastCue = cues[endIdx];
    // Build the combined text for the paragraph
    const text = cues
      .slice(groupStart, endIdx + 1)
      .map((c) => c.text)
      .join(" ")
      .replace(/\s+/g, " ")
      .trim();

    // Speaker label only when every cue in the paragraph shares the same speaker
    const speakers = new Set(
      cues.slice(groupStart, endIdx + 1).map((c) => c.speaker),
    );
    const speaker =
      speakers.size === 1 && groupSpeaker ? groupSpeaker : undefined;

    paragraphs.push({
      firstCueIndex: groupStart,
      lastCueIndex: endIdx,
      startMs: firstCue.startMs,
      endMs: lastCue.endMs,
      text,
      ...(speaker ? { speaker } : {}),
    });
  };

  for (let i = 1; i < cues.length; i++) {
    const prev = cues[i - 1];
    const curr = cues[i];

    const speakerChanged = curr.speaker !== prev.speaker;
    const gapMs = curr.startMs - prev.endMs;
    const gapTooLong = gapMs >= PARAGRAPH_GAP_THRESHOLD_MS;
    const textTooLong = accText.length >= PARAGRAPH_CHAR_LIMIT;

    if (speakerChanged || gapTooLong || textTooLong) {
      flush(i - 1);
      groupStart = i;
      accText = curr.text;
      groupSpeaker = curr.speaker;
    } else {
      accText += " " + curr.text;
    }
  }

  // Flush the last group
  flush(cues.length - 1);

  return paragraphs;
}

// ---------------------------------------------------------------------------
// Search
// ---------------------------------------------------------------------------

/**
 * Search cues for a case-insensitive substring match.
 *
 * Returns all matching cues with their index in the source cue array.
 */
export function searchTranscript(
  transcript: TranscriptData,
  query: string,
): TranscriptSearchResult {
  const trimmedQuery = query.trim();
  if (!trimmedQuery) return { query, matches: [] };

  const lower = trimmedQuery.toLowerCase();
  const matches: TranscriptSearchMatch[] = [];

  for (let i = 0; i < transcript.cues.length; i++) {
    const cue = transcript.cues[i];
    const idx = cue.text.toLowerCase().indexOf(lower);
    if (idx !== -1) {
      matches.push({ cueIndex: i, cue, matchIndex: idx });
    }
  }

  return { query: trimmedQuery, matches };
}

// ---------------------------------------------------------------------------
// Zod validation schema
// ---------------------------------------------------------------------------

export const transcriptCueSchema = z.object({
  id: z.string(),
  startMs: z.number().int().min(0),
  endMs: z.number().int().min(0),
  text: z.string(),
  speaker: z.string().optional(),
});

export const transcriptDataSchema = z.object({
  version: z.literal(1),
  language: z.string().min(1),
  source: z.enum(["manual", "auto"]),
  sourceProvider: z.string().optional(),
  sourceTrackId: z.string().optional(),
  lastFetchedAt: z.string().datetime({ offset: true }).optional(),
  isAutoGenerated: z.boolean(),
  cueCount: z.number().int().min(0),
  durationMs: z.number().int().min(0),
  cues: z.array(transcriptCueSchema),
});

/**
 * Validate a raw JSON value as a `TranscriptData` payload.
 * Returns the parsed payload on success, `null` on failure.
 */
export function validateTranscriptData(raw: unknown): TranscriptData | null {
  const result = transcriptDataSchema.safeParse(raw);
  return result.success ? result.data : null;
}

// ---------------------------------------------------------------------------
// Publish eligibility
// ---------------------------------------------------------------------------

/**
 * Reasons why a transcript is not publish-eligible.
 */
export type TranscriptIneligibleReason =
  | "missing"
  | "invalid_schema"
  | "no_cues";

/**
 * Result of checking transcript publish eligibility.
 */
export type TranscriptEligibility =
  | { eligible: true }
  | { eligible: false; reason: TranscriptIneligibleReason };

/**
 * Determine whether a lesson transcript is ready for publishing.
 *
 * Rules (from blueprint):
 *   - Non-video lessons are always eligible (pass `hasVideo = false`).
 *   - Video lessons with a valid transcript containing ≥1 cue are eligible.
 *   - Empty or missing transcripts block publish.
 */
export function checkTranscriptEligibility(
  transcription: unknown,
  hasVideo: boolean,
): TranscriptEligibility {
  if (!hasVideo) return { eligible: true };

  if (transcription === null || transcription === undefined) {
    return { eligible: false, reason: "missing" };
  }

  const parsed = validateTranscriptData(transcription);
  if (!parsed) {
    return { eligible: false, reason: "invalid_schema" };
  }

  if (parsed.cues.length === 0) {
    return { eligible: false, reason: "no_cues" };
  }

  return { eligible: true };
}

// ---------------------------------------------------------------------------
// Formatting helpers
// ---------------------------------------------------------------------------

/**
 * Format milliseconds as a human-readable timestamp string "M:SS" or "H:MM:SS".
 */
export function formatCueTime(ms: number): string {
  const totalSeconds = Math.floor(ms / 1000);
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  const ss = seconds.toString().padStart(2, "0");
  if (hours > 0) {
    const mm = minutes.toString().padStart(2, "0");
    return `${hours}:${mm}:${ss}`;
  }
  return `${minutes}:${ss}`;
}

/**
 * Find the index of the active cue at a given playback position.
 * Returns -1 when no cue spans the current time.
 */
export function findActiveCueIndex(
  cues: TranscriptCue[],
  positionMs: number,
): number {
  for (let i = 0; i < cues.length; i++) {
    if (positionMs >= cues[i].startMs && positionMs < cues[i].endMs) {
      return i;
    }
  }
  return -1;
}
